/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol

type ArrayOf<T> = Array<
  T & {
    _key: string
  }
>

// Source: ../../../../../../studio/schema.json
export type ChartConfig = {
  settings?: Code
  data?: Code
}

export type AudioCover = {
  color?: string
  anchor?: string
  backgroundColor?: string
}

export type AudioCoverCrop = {
  x?: number
  y?: number
  width?: number
  height?: number
}

export type ArticleCollectionReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'articleCollection'
}

export type ArticleReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'article'
}

export type PageReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'page'
}

export type Source = {
  sourceType?: 'COLLECTION' | 'QUERY' | 'MANUAL'
  collection?: ArticleCollectionReference
  query?: Code
  items?: ArrayOf<ArticleReference | PageReference>
}

export type SanityImageAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
}

export type Image1 = {
  asset?: SanityImageAssetReference
  media?: unknown // Unable to locate the referenced type "media1" in schema
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
  _type: 'image'
}

export type SearchBlock = {
  _type: 'searchBlock'
  enabled?: boolean
}

export type EditorBlock = {
  _type: 'editorBlock'
  content?: ArticleEditor
}

export type NewsletterReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'newsletter'
}

export type PodcastReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'podcast'
}

export type CallToAction = {
  _type: 'callToAction'
  target: NewsletterReference | ArticleCollectionReference | PodcastReference
  title?: string
  ctaText: string
}

export type Menu = {
  _type: 'menu'
  title?: string
  pages?: Array<
    {
      _key: string
    } & PageReference
  >
}

export type MeineRepublik = {
  _type: 'meineRepublik'
  enabled?: boolean
}

export type BestOfDialogue = {
  _type: 'bestOfDialogue'
  enabled?: boolean
}

export type TitleBlock = {
  _type: 'titleBlock'
  cover?: EditorialImage
  heading?: PageReference
}

export type TeaserList = {
  _type: 'teaserList'
  source?: Source
  appearance?: 'FRONT' | 'FEED' | 'OVERVIEW' | 'CAROUSEL'
  overviewLayout?: 'GRID' | 'COLUMN'
  maxItems?: number
  counter?: boolean
}

export type TeaserItem = {
  _type: 'teaserItem'
  reference: ArticleReference | PageReference
}

export type LegacyMeta = {
  _type: 'legacyMeta'
  template?: string
  audioCover?: AudioCover
  audioCoverCrop?: AudioCoverCrop
}

export type Mdast = {
  _type: 'mdast'
  content?: string
}

export type NestedEditor = Array<
  | {
      children?: Array<
        | {
            marks?: Array<string>
            text?: string
            _type: 'span'
            _key: string
          }
        | ({
            _key: string
          } & Variable)
        | ({
            _key: string
          } & VoiceTag)
      >
      style?: 'normal' | 'heading'
      listItem?: 'bullet' | 'number'
      markDefs?: Array<
        | ({
            _key: string
          } & Link)
        | ({
            _key: string
          } & InternalLink)
      >
      level?: number
      _type: 'block'
      _key: string
    }
  | ({
      _key: string
    } & Divider)
  | ({
      _key: string
    } & Button)
>

export type InlineEditor = Array<{
  children?: Array<{
    marks?: Array<string>
    text?: string
    _type: 'span'
    _key: string
  }>
  style?: 'normal'
  listItem?: never
  markDefs?: Array<
    | ({
        _key: string
      } & Link)
    | ({
        _key: string
      } & InternalLink)
  >
  level?: number
  _type: 'block'
  _key: string
}>

export type ArticleEditor = Array<
  | {
      children?: Array<
        | {
            marks?: Array<string>
            text?: string
            _type: 'span'
            _key: string
          }
        | ({
            _key: string
          } & Variable)
        | ({
            _key: string
          } & VoiceTag)
      >
      style?: 'normal' | 'heading' | 'note'
      listItem?: 'bullet' | 'number'
      markDefs?: Array<
        | ({
            _key: string
          } & Link)
        | ({
            _key: string
          } & InternalLink)
      >
      level?: number
      _type: 'block'
      _key: string
    }
  | ({
      _key: string
    } & EditorialImage)
  | ({
      _key: string
    } & ImageGroup)
  | ({
      _key: string
    } & InfoBox)
  | ({
      _key: string
    } & BlockQuote)
  | ({
      _key: string
    } & PullQuote)
  | ({
      _key: string
    } & WebOnly)
  | ({
      _key: string
    } & EmailOnly)
  | ({
      _key: string
    } & If)
  | ({
      _key: string
    } & IfNot)
  | ({
      _key: string
    } & Divider)
  | ({
      _key: string
    } & Chart)
  | ({
      _key: string
    } & EmbedVideo)
  | ({
      _key: string
    } & EmbedTwitter)
  | ({
      _key: string
    } & EmbedDataWrapper)
  | ({
      _key: string
    } & Html)
  | ({
      _key: string
    } & DynamicComponent)
  | ({
      _key: string
    } & StoryComponent)
  | ({
      _key: string
    } & SeriesNav)
  | ({
      _key: string
    } & Button)
>

export type Caption = {
  _type: 'caption'
  legend?: InlineEditor
  credit?: InlineEditor
}

export type VoiceTag = {
  _type: 'voiceTag'
  voice:
    | 'huebsch-01150-rpblk'
    | 'huebsch-62964-rpblk'
    | 'huebsch-714-109-rpblk'
    | 'huebsch-82170-rpblk'
    | 'huebsch-285-169-rpblk'
    | 'huebsch-gen-female-e-rpblk'
}

export type InternalLink = {
  _type: 'internalLink'
  reference?: ArticleReference | ArticleCollectionReference
}

export type DiscussionReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'discussion'
}

export type ContributorReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'contributor'
}

export type Article = {
  _id: string
  _type: 'article'
  _createdAt: string
  _updatedAt: string
  _rev: string
  cover?: EditorialImage
  heading?: PageReference
  title?: InlineEditor
  description?: InlineEditor
  byline?: InlineEditor
  publishDate?: string
  slug: Slug
  repoId?: string
  content?: ArticleEditor
  estimatedReadingMinutes?: number
  suppressSyntheticReadAloud?: boolean
  syntheticVoice?:
    | 'huebsch-01150-rpblk'
    | 'huebsch-62964-rpblk'
    | 'huebsch-714-109-rpblk'
    | 'huebsch-82170-rpblk'
    | 'huebsch-285-169-rpblk'
    | 'huebsch-gen-female-e-rpblk'
  audioSourceMp3?: string
  audioDurationMs?: number
  estimatedConsumptionMinutes?: number
  image?: Image1
  shortTitle?: InlineEditor
  shortLead?: InlineEditor
  frontTeaser?: FrontTeaser
  seo?: Seo
  feed?: boolean
  notificationTitle?: string
  articleCollection?: Array<
    {
      _key: string
    } & ArticleCollectionReference
  >
  emailSubject?: string
  newsletter?: NewsletterReference
  podcast?: PodcastReference
  discussion?: DiscussionReference
  inlineDiscussion?: boolean
  articleRecommendations?: Array<
    {
      _key: string
    } & ArticleReference
  >
  contributors?: Array<{
    kind?: string
    contributor?: ContributorReference
    _type: 'contributorEntry'
    _key: string
  }>
  readingAccess?: 'OPEN' | 'PAYNOTE' | 'REGWALL'
  showTextProgress?: boolean
  theme?: Theme
  mdast?: Mdast
  publikatorMeta?: LegacyMeta
}

export type Theme = {
  _type: 'theme'
  titleFont?: 'SERIF' | 'SANS'
  bodyFont?: 'SERIF' | 'SANS'
  accentColor?: Color
  backgroundColor?: Color
  darkMode?: boolean
}

export type Contributor = {
  _id: string
  _type: 'contributor'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  description?: string
  portrait?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  userId?: string
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top: number
  bottom: number
  left: number
  right: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x: number
  y: number
  height: number
  width: number
}

export type Discussion = {
  _id: string
  _type: 'discussion'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  discussionClosed?: boolean
  commentsMaxLength?: number
  commentsMinInterval?: number
  discussionAnonymity?: 'ALLOWED' | 'ENFORCED' | 'FORBIDDEN'
  tags?: Array<string>
  tagRequired?: boolean
}

export type Podcast = {
  _id: string
  _type: 'podcast'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  appleUrl?: string
  spotifyUrl?: string
  podigeeSlug?: string
}

export type Newsletter = {
  _id: string
  _type: 'newsletter'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  description?: string
  frequency?: string
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  name: string
  replyTo?: string
  fromName?: string
  savedSegmentId?: number
}

export type Slug = {
  _type: 'slug'
  current: string
  source?: string
}

export type Page = {
  _id: string
  _type: 'page'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: InlineEditor
  description?: InlineEditor
  publishDate?: string
  slug: Slug
  repoId?: string
  pageBuilder?: Array<
    | ({
        _key: string
      } & TitleBlock)
    | ({
        _key: string
      } & TeaserItem)
    | ({
        _key: string
      } & TeaserList)
    | ({
        _key: string
      } & EditorBlock)
    | ({
        _key: string
      } & CallToAction)
    | ({
        _key: string
      } & Menu)
    | ({
        _key: string
      } & SearchBlock)
    | ({
        _key: string
      } & BestOfDialogue)
    | ({
        _key: string
      } & MeineRepublik)
  >
  image?: Image1
  shortTitle?: InlineEditor
  shortLead?: InlineEditor
  frontTeaser?: FrontTeaser
  seo?: Seo
  theme?: Theme
}

export type Seo = {
  _type: 'seo'
  title?: string
  description?: string
  useImageBuilder?: boolean
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  imageBuilder?: SeoImageBuilder
}

export type FrontTeaser = {
  _type: 'frontTeaser'
  layout?: 'VIGNETTE' | 'TEXT' | 'IMAGE' | 'SPLIT'
  title?: InlineEditor
  lead?: InlineEditor
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  imageCredits?: string
  imagePosition?: 'LEFT' | 'RIGHT'
  imagePadding?: boolean
  textSize?: 'SMALL' | 'MEDIUM' | 'LARGE' | 'STANDARD'
  textPosition?:
    | 'TOP'
    | 'MIDDLE'
    | 'BOTTOM'
    | 'TOP_LEFT'
    | 'TOP_RIGHT'
    | 'BOTTOM_LEFT'
    | 'BOTTOM_RIGHT'
    | 'UNDERNEATH'
  color?: Color
  backgroundColor?: Color
}

export type Code = {
  _type: 'code'
  language?: string
  filename?: string
  code?: string
  highlightedLines?: Array<number>
}

export type EditorialImage = {
  _type: 'editorialImage'
  asset?: SanityImageAssetReference
  media?: unknown
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
  imageDark?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  alt?: string
  caption?: Caption
  size?: 'NORMAL' | 'BREAKOUT' | 'FULL'
}

export type Link = {
  _type: 'link'
  href?: string
}

export type Variable = {
  _type: 'variable'
  name?: string
}

export type IfNot = {
  _type: 'ifNot'
  present?: string
  body?: NestedEditor
}

export type If = {
  _type: 'if'
  present?: string
  body?: NestedEditor
}

export type EmailOnly = {
  _type: 'emailOnly'
  body?: NestedEditor
}

export type WebOnly = {
  _type: 'webOnly'
  body?: NestedEditor
}

export type PullQuote = {
  _type: 'pullQuote'
  text?: string
  source?: string
  image?: AsideImage
  size?: 'narrow' | 'float' | 'breakout'
}

export type AsideImage = {
  _type: 'asideImage'
  asset?: SanityImageAssetReference
  media?: unknown
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
  alt?: string
  caption?: Caption
}

export type BlockQuote = {
  _type: 'blockQuote'
  body?: NestedEditor
  caption?: Caption
}

export type InfoBox = {
  _type: 'infoBox'
  title?: string
  image?: AsideImage
  body?: NestedEditor
  size?: 'float' | 'breakout'
  figureSize?: 'S' | 'M' | 'L'
  figureFloat?: boolean
  collapsible?: boolean
}

export type Button = {
  _type: 'button'
  text?: string
  url?: string
}

export type SeriesNav = {
  _type: 'seriesNav'
  series: ArticleCollectionReference
}

export type ArticleCollection = {
  _id: string
  _type: 'articleCollection'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  description?: string
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
}

export type StoryComponent = {
  _type: 'storyComponent'
  url?: string
  tagname?: string
  componentData?: Code
  size?: 'NORMAL' | 'BREAKOUT' | 'FULL'
}

export type DynamicComponent = {
  _type: 'dynamicComponent'
  size?: 'NORMAL' | 'BREAKOUT' | 'FULL'
  src?: string
  identifier?: string
  props?: Code
  autoHtml?: boolean
  html?: Code
}

export type Html = {
  _type: 'html'
  html?: string
}

export type EmbedDataWrapper = {
  _type: 'embedDataWrapper'
  datawrapperId?: string
  forceDark?: boolean
  plain?: boolean
  size?: 'NORMAL' | 'BREAKOUT' | 'FULL'
}

export type EmbedTwitter = {
  _type: 'embedTwitter'
  data?: string
}

export type EmbedVideo = {
  _type: 'embedVideo'
  data?: string
}

export type Chart = {
  _type: 'chart'
  title?: InlineEditor
  lead?: InlineEditor
  chartConfig?: ChartConfig
  source?: InlineEditor
  size?: 'FLOAT_TINY' | 'NARROW' | 'NORMAL' | 'BREAKOUT'
}

export type Divider = {
  _type: 'divider'
  style?: string
}

export type ImageGroup = {
  _type: 'imageGroup'
  images?: Array<
    {
      _key: string
    } & GroupedEditorialImage
  >
  caption?: Caption
  size?: 'NARROW' | 'NORMAL' | 'BREAKOUT'
}

export type GroupedEditorialImage = {
  _type: 'groupedEditorialImage'
  asset?: SanityImageAssetReference
  media?: unknown
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
  imageDark?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  alt?: string
  caption?: Caption
}

export type Color = {
  _type: 'color'
  hex?: string
  alpha?: number
  hsl?: HslaColor
  hsv?: HsvaColor
  rgb?: RgbaColor
}

export type SeoImageBuilder = {
  _type: 'seoImageBuilder'
  text?: string
  fontSize?: number
  textPosition?: 'top' | 'center' | 'bottom'
  inverted?: boolean
  layout?: 'TEXT' | 'BACKGROUND_IMAGE' | 'LOGO'
  backgroundImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  logo?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
}

export type MediaTag = {
  _id: string
  _type: 'media.tag'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: Slug
}

export type RgbaColor = {
  _type: 'rgbaColor'
  r?: number
  g?: number
  b?: number
  a?: number
}

export type HsvaColor = {
  _type: 'hsvaColor'
  h?: number
  s?: number
  v?: number
  a?: number
}

export type HslaColor = {
  _type: 'hslaColor'
  h?: number
  s?: number
  l?: number
  a?: number
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height: number
  width: number
  aspectRatio: number
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  thumbHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash: string
  extension: string
  mimeType: string
  size: number
  assetId: string
  uploadId?: string
  path: string
  url: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash: string
  extension: string
  mimeType: string
  size: number
  assetId: string
  uploadId?: string
  path: string
  url: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type AllSanitySchemaTypes =
  | ChartConfig
  | AudioCover
  | AudioCoverCrop
  | ArticleCollectionReference
  | ArticleReference
  | PageReference
  | Source
  | SanityImageAssetReference
  | Image1
  | SearchBlock
  | EditorBlock
  | NewsletterReference
  | PodcastReference
  | CallToAction
  | Menu
  | MeineRepublik
  | BestOfDialogue
  | TitleBlock
  | TeaserList
  | TeaserItem
  | LegacyMeta
  | Mdast
  | NestedEditor
  | InlineEditor
  | ArticleEditor
  | Caption
  | VoiceTag
  | InternalLink
  | DiscussionReference
  | ContributorReference
  | Article
  | Theme
  | Contributor
  | SanityImageCrop
  | SanityImageHotspot
  | Discussion
  | Podcast
  | Newsletter
  | Slug
  | Page
  | Seo
  | FrontTeaser
  | Code
  | EditorialImage
  | Link
  | Variable
  | IfNot
  | If
  | EmailOnly
  | WebOnly
  | PullQuote
  | AsideImage
  | BlockQuote
  | InfoBox
  | Button
  | SeriesNav
  | ArticleCollection
  | StoryComponent
  | DynamicComponent
  | Html
  | EmbedDataWrapper
  | EmbedTwitter
  | EmbedVideo
  | Chart
  | Divider
  | ImageGroup
  | GroupedEditorialImage
  | Color
  | SeoImageBuilder
  | MediaTag
  | RgbaColor
  | HsvaColor
  | HslaColor
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint

// Source: src/app/(sanity)/articles/[...path]/components/article-content.tsx
// Variable: ARTICLE_CONTENT_QUERY
// Query: *[_type == "article" && slug.current == $slug][0]{    _id,    content[]{        ...,        markDefs[]{          ...,          _type == "internalLink" => {            "slug": @.reference->slug          }        }    }  }
export type ARTICLE_CONTENT_QUERY_RESULT = {
  _id: string
  content: Array<
    | {
        children?: Array<
          | ({
              _key: string
            } & Variable)
          | ({
              _key: string
            } & VoiceTag)
          | {
              marks?: Array<string>
              text?: string
              _type: 'span'
              _key: string
            }
        >
        style?: 'heading' | 'normal' | 'note'
        listItem?: 'bullet' | 'number'
        markDefs: Array<
          | {
              _key: string
              _type: 'internalLink'
              reference?: ArticleReference | ArticleCollectionReference
              slug: Slug | null
            }
          | {
              _key: string
              _type: 'link'
              href?: string
            }
        > | null
        level?: number
        _type: 'block'
        _key: string
      }
    | {
        _key: string
        _type: 'blockQuote'
        body?: NestedEditor
        caption?: Caption
        markDefs: null
      }
    | {
        _key: string
        _type: 'button'
        text?: string
        url?: string
        markDefs: null
      }
    | {
        _key: string
        _type: 'chart'
        title?: InlineEditor
        lead?: InlineEditor
        chartConfig?: ChartConfig
        source?: InlineEditor
        size?: 'BREAKOUT' | 'FLOAT_TINY' | 'NARROW' | 'NORMAL'
        markDefs: null
      }
    | {
        _key: string
        _type: 'divider'
        style?: string
        markDefs: null
      }
    | {
        _key: string
        _type: 'dynamicComponent'
        size?: 'BREAKOUT' | 'FULL' | 'NORMAL'
        src?: string
        identifier?: string
        props?: Code
        autoHtml?: boolean
        html?: Code
        markDefs: null
      }
    | {
        _key: string
        _type: 'editorialImage'
        asset?: SanityImageAssetReference
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        imageDark?: {
          asset?: SanityImageAssetReference
          media?: unknown
          hotspot?: SanityImageHotspot
          crop?: SanityImageCrop
          _type: 'image'
        }
        alt?: string
        caption?: Caption
        size?: 'BREAKOUT' | 'FULL' | 'NORMAL'
        markDefs: null
      }
    | {
        _key: string
        _type: 'emailOnly'
        body?: NestedEditor
        markDefs: null
      }
    | {
        _key: string
        _type: 'embedDataWrapper'
        datawrapperId?: string
        forceDark?: boolean
        plain?: boolean
        size?: 'BREAKOUT' | 'FULL' | 'NORMAL'
        markDefs: null
      }
    | {
        _key: string
        _type: 'embedTwitter'
        data?: string
        markDefs: null
      }
    | {
        _key: string
        _type: 'embedVideo'
        data?: string
        markDefs: null
      }
    | {
        _key: string
        _type: 'html'
        html?: string
        markDefs: null
      }
    | {
        _key: string
        _type: 'if'
        present?: string
        body?: NestedEditor
        markDefs: null
      }
    | {
        _key: string
        _type: 'ifNot'
        present?: string
        body?: NestedEditor
        markDefs: null
      }
    | {
        _key: string
        _type: 'imageGroup'
        images?: Array<
          {
            _key: string
          } & GroupedEditorialImage
        >
        caption?: Caption
        size?: 'BREAKOUT' | 'NARROW' | 'NORMAL'
        markDefs: null
      }
    | {
        _key: string
        _type: 'infoBox'
        title?: string
        image?: AsideImage
        body?: NestedEditor
        size?: 'breakout' | 'float'
        figureSize?: 'L' | 'M' | 'S'
        figureFloat?: boolean
        collapsible?: boolean
        markDefs: null
      }
    | {
        _key: string
        _type: 'pullQuote'
        text?: string
        source?: string
        image?: AsideImage
        size?: 'breakout' | 'float' | 'narrow'
        markDefs: null
      }
    | {
        _key: string
        _type: 'seriesNav'
        series: ArticleCollectionReference
        markDefs: null
      }
    | {
        _key: string
        _type: 'storyComponent'
        url?: string
        tagname?: string
        componentData?: Code
        size?: 'BREAKOUT' | 'FULL' | 'NORMAL'
        markDefs: null
      }
    | {
        _key: string
        _type: 'webOnly'
        body?: NestedEditor
        markDefs: null
      }
  > | null
} | null

// Source: src/app/(sanity)/articles/[...path]/components/series-nav.tsx
// Variable: SERIES_NAV_QUERY
// Query: *[_type == "articleCollection" && _id == $id][0]{    _id,    title,    description,    image,    "episodes": *[_type == "article" && references(^._id)]{      _id,      title,      description,      image    }  }
export type SERIES_NAV_QUERY_RESULT = {
  _id: string
  title: string
  description: string | null
  image: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  } | null
  episodes: Array<{
    _id: string
    title: InlineEditor | null
    description: InlineEditor | null
    image: Image1 | null
  }>
} | null

// Source: src/app/(sanity)/articles/[...path]/page.tsx
// Variable: ARTICLE_SEO_QUERY
// Query: *[_type == "article" && slug.current == $slug][0]{    "title": coalesce(seo.title, pt::text(title)),    "description": coalesce(seo.description, pt::text(description))  }
export type ARTICLE_SEO_QUERY_RESULT = {
  title: string
  description: string
} | null

// Source: src/app/(sanity)/articles/[...path]/page.tsx
// Variable: ARTICLE_QUERY
// Query: *[_type == "article" && slug.current == $slug][0]{    _id,    title,    description,    seo {      title,      description    },    articleCollection->{      title,      description,      image    },    newsletter->{      title,      description,      frequency,      image,      name,    },    theme {      darkMode,      color    },    contributors[]{      _id,      kind,      "slug": contributor->userId,      "name": contributor->title,      "description": contributor->description,      "portrait": contributor->portrait    },    articleRecommendations[]->{      _id,      title,      description,      slug,      "collection": articleCollection->title,      theme {        color      },      contributors[]{        kind,        "name": contributor->title,      }    }  }
export type ARTICLE_QUERY_RESULT = {
  _id: string
  title: InlineEditor | null
  description: InlineEditor | null
  seo: {
    title: string | null
    description: string | null
  } | null
  articleCollection: null
  newsletter: {
    title: string
    description: string | null
    frequency: string | null
    image: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
    } | null
    name: string
  } | null
  theme: {
    darkMode: boolean | null
    color: null
  } | null
  contributors: Array<{
    _id: null
    kind: string | null
    slug: string | null
    name: string | null
    description: string | null
    portrait: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
    } | null
  }> | null
  articleRecommendations: Array<{
    _id: string
    title: InlineEditor | null
    description: InlineEditor | null
    slug: Slug
    collection: null
    theme: {
      color: null
    } | null
    contributors: Array<{
      kind: string | null
      name: string | null
    }> | null
  }> | null
} | null

// Source: src/app/(sanity)/articles/page.tsx
// Variable: ARTICLES_QUERY
// Query: *[_type == "article" && defined(slug.current)][0...100]{    "slug": slug.current,    title  }
export type ARTICLES_QUERY_RESULT = Array<{
  slug: string
  title: InlineEditor | null
}>

// Query TypeMap
import '@sanity/client'
declare module '@sanity/client' {
  interface SanityQueries {
    '*[_type == "article" && slug.current == $slug][0]{\n    _id,\n    content[]{\n        ...,\n        markDefs[]{\n          ...,\n          _type == "internalLink" => {\n            "slug": @.reference->slug\n          }\n        }\n    }\n  }': ARTICLE_CONTENT_QUERY_RESULT
    '*[_type == "articleCollection" && _id == $id][0]{\n    _id,\n    title,\n    description,\n    image,\n\n    "episodes": *[_type == "article" && references(^._id)]{\n      _id,\n      title,\n      description,\n      image\n    }\n  }': SERIES_NAV_QUERY_RESULT
    '*[_type == "article" && slug.current == $slug][0]{\n    "title": coalesce(seo.title, pt::text(title)),\n    "description": coalesce(seo.description, pt::text(description))\n  }': ARTICLE_SEO_QUERY_RESULT
    '*[_type == "article" && slug.current == $slug][0]{\n    _id,\n    title,\n    description,\n    seo {\n      title,\n      description\n    },\n    articleCollection->{\n      title,\n      description,\n      image\n    },\n    newsletter->{\n      title,\n      description,\n      frequency,\n      image,\n      name,\n    },\n    theme {\n      darkMode,\n      color\n    },\n    contributors[]{\n      _id,\n      kind,\n      "slug": contributor->userId,\n      "name": contributor->title,\n      "description": contributor->description,\n      "portrait": contributor->portrait\n    },\n    articleRecommendations[]->{\n      _id,\n      title,\n      description,\n      slug,\n      "collection": articleCollection->title,\n      theme {\n        color\n      },\n      contributors[]{\n        kind,\n        "name": contributor->title,\n      }\n    }\n  }': ARTICLE_QUERY_RESULT
    '\n  *[_type == "article" && defined(slug.current)][0...100]{\n    "slug": slug.current,\n    title\n  }': ARTICLES_QUERY_RESULT
  }
}
