import assert from 'node:assert'
const DEFAULT_SCHEMA_NAME = 'payments'
// const DEFAULT_STRIPE_API_VERSION = '2020-08-27'
const STRIPE_CUSTOM_CHECKOUT_API_VERSION = '2020-08-27; custom_checkout_beta=v1'

export type Config = {
  SCHEMA_NAME: string
  SHOP_BASE_URL: string
  PROJECT_R_STRIPE_API_KEY: string
  REPUBLIK_STRIPE_API_KEY: string
  STRIPE_API_VERSION: string
  PROJECT_R_STRIPE_ENDPOINT_SECRET: string
  REPUBLIK_STRIPE_ENDPOINT_SECRET: string
  MONTHLY_SUBSCRIPTION_STRIPE_PRODUCT_ID: string
  YEARLY_SUBSCRIPTION_STRIPE_PRODUCT_ID: string
  BENEFACTOR_SUBSCRIPTION_STRIPE_PRODUCT_ID: string
  REPUBLIK_STRIPE_SUBSCRIPTION_TAX_ID: string
  REPUBLIK_STRIPE_PAYMENTS_CONFIG_ID: string
  PROJECT_R_STRIPE_PAYMENTS_CONFIG_ID: string
  REPUBLIK_3_MONTH_GIFT_COUPON: string
  PROJECT_R_3_MONTH_GIFT_COUPON: string
  PROJECT_R_YEARLY_GIFT_COUPON: string
  PROJECT_R_REDUCED_MEMBERSHIP_DISCOUNTS: string[]
  PROJECT_R_DONATION_PRODUCT_ID: string
}

export function getConfig(): Config {
  assert(
    typeof process.env.SHOP_BASE_URL !== 'undefined',
    'SHOP_BASE_URL not set',
  )
  assert(
    typeof process.env.STRIPE_SECRET_KEY_PROJECT_R !== 'undefined',
    'STRIPE_SECRET_KEY_PROJECT_R not set',
  )
  assert(
    typeof process.env.STRIPE_SECRET_KEY_REPUBLIK !== 'undefined',
    'STRIPE_SECRET_KEY_REPUBLIK not set',
  )
  assert(
    typeof process.env.PAYMENTS_PROJECT_R_STRIPE_ENDPOINT_SECRET !==
      'undefined',
    'PAYMENTS PROJECT R Stripe webhook secret not set',
  )
  assert(
    typeof process.env.PAYMENTS_REPUBLIK_STRIPE_ENDPOINT_SECRET !== 'undefined',
    'PAYMENTS REPUBLIK AG Stripe webhook secret not set',
  )
  assert(
    typeof process.env.YEARLY_SUBSCRIPTION_STRIPE_PRODUCT_ID !== 'undefined',
    'YEARLY_SUBSCRIPTION_STRIPE_PRODUCT_ID not set',
  )
  assert(
    typeof process.env.MONTHLY_SUBSCRIPTION_STRIPE_PRODUCT_ID !== 'undefined',
    'MONTHLY_SUBSCRIPTION_STRIPE_PRODUCT_ID not set',
  )
  assert(
    typeof process.env.PAYMENTS_REPUBLIK_STRIPE_SUBSCRIPTION_TAX_ID !==
      'undefined',
    'PAYMENTS_REPUBLIK_STRIPE_SUBSCRIPTION_TAX_ID not set',
  )
  assert(
    typeof process.env.PAYMENTS_PROJECT_R_STRIPE_PAYMENTS_CONFIG_ID !==
      'undefined',
    'PAYMENTS_PROJECT_R_STRIPE_PAYMENTS_CONFIG_ID not set',
  )
  assert(
    typeof process.env.PAYMENTS_REPUBLIK_STRIPE_PAYMENTS_CONFIG_ID !==
      'undefined',
    'PAYMENTS_REPUBLIK_STRIPE_PAYMENTS_CONFIG_ID not set',
  )

  assert(
    typeof process.env.PAYMENTS_PROJECT_R_3_MONTH_GIFT_COUPON !== 'undefined',
    'PAYMENTS_PROJECT_R_3_MONTH_GIFT_COUPON not set',
  )

  assert(
    typeof process.env.PAYMENTS_REPUBLIK_3_MONTH_GIFT_COUPON !== 'undefined',
    'PAYMENTS_REPUBLIK_3_MONTH_GIFT_COUPON not set',
  )

  assert(
    typeof process.env.PAYMENTS_PROJECT_R_YEARLY_GIFT_COUPON !== 'undefined',
    'PAYMENTS_PROJECT_R_YEARLY_GIFT_COUPON not set',
  )

  assert(
    typeof process.env.PAYMENTS_PROJECT_R_DONATION_PRODUCT_ID !== 'undefined',
    'PAYMENTS_PROJECT_R_DONATION_PRODUCT_ID not set',
  )

  assert(
    typeof process.env.PAYMENTS_BENEFACTOR_SUBSCRIPTION_STRIPE_PRODUCT_ID !==
      'undefined',
    'PAYMENTS_BENEFACTOR_SUBSCRIPTION_STRIPE_PRODUCT_ID not set',
  )

  return {
    SCHEMA_NAME: DEFAULT_SCHEMA_NAME,
    SHOP_BASE_URL: process.env.SHOP_BASE_URL,
    PROJECT_R_STRIPE_API_KEY: process.env.STRIPE_SECRET_KEY_PROJECT_R,
    REPUBLIK_STRIPE_API_KEY: process.env.STRIPE_SECRET_KEY_REPUBLIK,
    STRIPE_API_VERSION: STRIPE_CUSTOM_CHECKOUT_API_VERSION,
    PROJECT_R_STRIPE_ENDPOINT_SECRET:
      process.env.PAYMENTS_PROJECT_R_STRIPE_ENDPOINT_SECRET,
    REPUBLIK_STRIPE_ENDPOINT_SECRET:
      process.env.PAYMENTS_REPUBLIK_STRIPE_ENDPOINT_SECRET,
    YEARLY_SUBSCRIPTION_STRIPE_PRODUCT_ID:
      process.env.YEARLY_SUBSCRIPTION_STRIPE_PRODUCT_ID,
    MONTHLY_SUBSCRIPTION_STRIPE_PRODUCT_ID:
      process.env.MONTHLY_SUBSCRIPTION_STRIPE_PRODUCT_ID,
    REPUBLIK_STRIPE_SUBSCRIPTION_TAX_ID:
      process.env.PAYMENTS_REPUBLIK_STRIPE_SUBSCRIPTION_TAX_ID,
    PROJECT_R_STRIPE_PAYMENTS_CONFIG_ID:
      process.env.PAYMENTS_PROJECT_R_STRIPE_PAYMENTS_CONFIG_ID,
    REPUBLIK_STRIPE_PAYMENTS_CONFIG_ID:
      process.env.PAYMENTS_REPUBLIK_STRIPE_PAYMENTS_CONFIG_ID,
    PROJECT_R_3_MONTH_GIFT_COUPON:
      process.env.PAYMENTS_PROJECT_R_3_MONTH_GIFT_COUPON,
    PROJECT_R_YEARLY_GIFT_COUPON:
      process.env.PAYMENTS_PROJECT_R_YEARLY_GIFT_COUPON,
    REPUBLIK_3_MONTH_GIFT_COUPON:
      process.env.PAYMENTS_REPUBLIK_3_MONTH_GIFT_COUPON,
    PROJECT_R_REDUCED_MEMBERSHIP_DISCOUNTS:
      process.env.PAYMENTS_PROJECT_R_REDUCED_MEMBERSHIP_DISCOUNTS?.split(';') ||
      [],
    PROJECT_R_DONATION_PRODUCT_ID:
      process.env.PAYMENTS_PROJECT_R_DONATION_PRODUCT_ID,
    BENEFACTOR_SUBSCRIPTION_STRIPE_PRODUCT_ID:
      process.env.PAYMENTS_BENEFACTOR_SUBSCRIPTION_STRIPE_PRODUCT_ID,
  }
}
