fragment SubscriptionInfo on Subscription {
  id
  isEligibleForNotifications
  active
  filters
  object {
    ... on User {
      id
      name
    }
    ... on Document {
      id
      meta {
        title
      }
    }
  }
}
