query CampaignSender($campaignSlug: String!) {
  me {
    id
    hasPublicProfile
    username
    referralCode
    activeMembership {
      type {
        name
      }
    }
    referrals(campaignSlug: $campaignSlug) {
      count
    }
  }
}
