query CampaignInvitee($referralCode: String!) {
  me {
    id
    activeMembership {
      type {
        id
        name
      }
    }
  }
  sender: user(referralCode: $referralCode) {
    id
    firstName
    lastName
    portrait
    username
  }
}
