query UserInviterProfileInfo($accessToken: ID) {
  me {
    id
    activeMembership {
      type {
        id
        name
      }
    }
  }
  sender: user(accessToken: $accessToken) {
    id
    firstName
    lastName
    portrait
    futureCampaignAboCount
  }
}
