query MarketingLandingPageCMS {
  marketingLandingPage {
    id
    reasons {
      title
      description
    }
    formats {
      imageDark {
        responsiveImage(imgixParams: { w: 160 }) {
          src
        }
      }
      imageBright {
        responsiveImage(imgixParams: { w: 160 }) {
          src
        }
      }
      title
      description
      color {
        hex
      }
    }
    sectionTeamTitle
    sectionTeamDescription
    sectionDialogTitle
    sectionDialogDescription
    sectionFormatsTitle
    sectionFormatsDescription
  }
}
