const {
  MAILCHIMP_INTEREST_NEWSLETTER_DAILY: _MAILCHIMP_INTEREST_NEWSLETTER_DAILY,
  MAILCHIMP_INTEREST_NEWSLETTER_WEEKLY: _MAILCHIMP_INTEREST_NEWSLETTER_WEEKLY,
  MAILCHIMP_INTEREST_NEWSLETTER_PROJECTR:
    _MAILCHIMP_INTEREST_NEWSLETTER_PROJECTR,
  MAILCHIMP_INTEREST_NEWSLETTER_CLIMATE: _MAILCHIMP_INTEREST_NEWSLETTER_CLIMATE,
  MAILCHIMP_INTEREST_NEWSLETTER_WDWWW: _MAILCHIMP_INTEREST_NEWSLETTER_WDWWW,
  MAILCHIMP_INTEREST_NEWSLETTER_ACCOMPLICE:
    _MAILCHIMP_INTEREST_NEWSLETTER_ACCOMPLICE,
  MAILCHIMP_INTEREST_MEMBER: _MAILCHIMP_INTEREST_MEMBER,
  MAILCHIMP_INTEREST_MEMBER_BENEFACTOR: _MAILCHIMP_INTEREST_MEMBER_BENEFACTOR,
  MAILCHIMP_MAIN_LIST_ID: _MAILCHIMP_MAIN_LIST_ID,
  MAILCHIMP_ONBOARDING_AUDIENCE_ID: _MAILCHIMP_ONBOARDING_AUDIENCE_ID,
  MAILCHIMP_MARKETING_AUDIENCE_ID: _MAILCHIMP_MARKETING_AUDIENCE_ID,
  MAILCHIMP_PROBELESEN_AUDIENCE_ID: _MAILCHIMP_PROBELESEN_AUDIENCE_ID,
  MAILCHIMP_PRODUKTINFOS_AUDIENCE_ID: _MAILCHIMP_PRODUKTINFOS_AUDIENCE_ID,
  MAILCHIMP_INTEREST_PLEDGE: _MAILCHIMP_INTEREST_PLEDGE,
  MAILCHIMP_INTEREST_GRANTED_ACCESS: _MAILCHIMP_INTEREST_GRANTED_ACCESS,
} = process.env

assertEnvVariableExists(
  _MAILCHIMP_INTEREST_NEWSLETTER_DAILY,
  'MAILCHIMP_INTEREST_NEWSLETTER_DAILY',
)
assertEnvVariableExists(
  _MAILCHIMP_INTEREST_NEWSLETTER_WEEKLY,
  'MAILCHIMP_INTEREST_NEWSLETTER_WEEKLY',
)
assertEnvVariableExists(
  _MAILCHIMP_INTEREST_NEWSLETTER_PROJECTR,
  'MAILCHIMP_INTEREST_NEWSLETTER_PROJECTR',
)
assertEnvVariableExists(
  _MAILCHIMP_INTEREST_NEWSLETTER_CLIMATE,
  'MAILCHIMP_INTEREST_NEWSLETTER_CLIMATE',
)
assertEnvVariableExists(
  _MAILCHIMP_INTEREST_NEWSLETTER_WDWWW,
  'MAILCHIMP_INTEREST_NEWSLETTER_WDWWW',
)
assertEnvVariableExists(
  _MAILCHIMP_INTEREST_NEWSLETTER_ACCOMPLICE,
  'MAILCHIMP_INTEREST_NEWSLETTER_ACCOMPLICE',
)

assertEnvVariableExists(_MAILCHIMP_INTEREST_MEMBER, 'MAILCHIMP_INTEREST_MEMBER')
assertEnvVariableExists(
  _MAILCHIMP_INTEREST_MEMBER_BENEFACTOR,
  'MAILCHIMP_INTEREST_MEMBER_BENEFACTOR',
)
assertEnvVariableExists(_MAILCHIMP_MAIN_LIST_ID, 'MAILCHIMP_MAIN_LIST_ID')
assertEnvVariableExists(
  _MAILCHIMP_ONBOARDING_AUDIENCE_ID,
  'MAILCHIMP_ONBOARDING_AUDIENCE_ID',
)
assertEnvVariableExists(
  _MAILCHIMP_MARKETING_AUDIENCE_ID,
  'MAILCHIMP_MARKETING_AUDIENCE_ID',
)
assertEnvVariableExists(
  _MAILCHIMP_PROBELESEN_AUDIENCE_ID,
  'MAILCHIMP_PROBELESEN_AUDIENCE_ID',
)
assertEnvVariableExists(
  _MAILCHIMP_PRODUKTINFOS_AUDIENCE_ID,
  'MAILCHIMP_PRODUKTINFOS_AUDIENCE_ID',
)
assertEnvVariableExists(_MAILCHIMP_INTEREST_PLEDGE, 'MAILCHIMP_INTEREST_PLEDGE')
assertEnvVariableExists(_MAILCHIMP_INTEREST_GRANTED_ACCESS, 'MAILCHIMP_INTEREST_GRANTED_ACCESS')

export function assertEnvVariableExists(
  envVariable: string | undefined,
  envVariableName: string,
): asserts envVariable is string {
  if (!envVariable) {
    throw new Error(`Env-Variable ${envVariableName} is missing.`)
  }
}

export const MAILCHIMP_INTEREST_NEWSLETTER_DAILY =
  _MAILCHIMP_INTEREST_NEWSLETTER_DAILY
export const MAILCHIMP_INTEREST_NEWSLETTER_WEEKLY =
  _MAILCHIMP_INTEREST_NEWSLETTER_WEEKLY
export const MAILCHIMP_INTEREST_NEWSLETTER_PROJECTR =
  _MAILCHIMP_INTEREST_NEWSLETTER_PROJECTR
export const MAILCHIMP_INTEREST_NEWSLETTER_CLIMATE =
  _MAILCHIMP_INTEREST_NEWSLETTER_CLIMATE
export const MAILCHIMP_INTEREST_NEWSLETTER_WDWWW =
  _MAILCHIMP_INTEREST_NEWSLETTER_WDWWW
export const MAILCHIMP_INTEREST_NEWSLETTER_ACCOMPLICE =
  _MAILCHIMP_INTEREST_NEWSLETTER_ACCOMPLICE
export const MAILCHIMP_INTEREST_MEMBER = _MAILCHIMP_INTEREST_MEMBER
export const MAILCHIMP_INTEREST_MEMBER_BENEFACTOR =
  _MAILCHIMP_INTEREST_MEMBER_BENEFACTOR
export const MAILCHIMP_MAIN_LIST_ID = _MAILCHIMP_MAIN_LIST_ID
export const MAILCHIMP_ONBOARDING_AUDIENCE_ID =
  _MAILCHIMP_ONBOARDING_AUDIENCE_ID
export const MAILCHIMP_MARKETING_AUDIENCE_ID = _MAILCHIMP_MARKETING_AUDIENCE_ID
export const MAILCHIMP_PROBELESEN_AUDIENCE_ID =
  _MAILCHIMP_PROBELESEN_AUDIENCE_ID
export const MAILCHIMP_PRODUKTINFOS_AUDIENCE_ID =
  _MAILCHIMP_PRODUKTINFOS_AUDIENCE_ID
export const MAILCHIMP_INTEREST_PLEDGE = _MAILCHIMP_INTEREST_PLEDGE
export const MAILCHIMP_INTEREST_GRANTED_ACCESS = _MAILCHIMP_INTEREST_GRANTED_ACCESS
