assertEnvVariableExists(process.env, [
  'MAILCHIMP_INTEREST_NEWSLETTER_DAILY',
  'MAILCHIMP_INTEREST_NEWSLETTER_WEEKLY',
  'MAILCHIMP_INTEREST_NEWSLETTER_PROJECTR',
  'MAILCHIMP_INTEREST_NEWSLETTER_CLIMATE',
  'MAILCHIMP_INTEREST_NEWSLETTER_WDWWW',
  'MAILCHIMP_INTEREST_NEWSLETTER_SUNDAY',
  'MAILCHIMP_INTEREST_NEWSLETTER_BAB',
  'MAILCHIMP_INTEREST_NEWSLETTER_ACCOMPLICE',
  'MAILCHIMP_INTEREST_MEMBER',
  'MAILCHIMP_INTEREST_MEMBER_BENEFACTOR',
  'MAILCHIMP_INTEREST_PAST_REGWALL_TRIAL',
  'MAILCHIMP_MAIN_LIST_ID',
  'MAILCHIMP_ONBOARDING_AUDIENCE_ID',
  'MAILCHIMP_MARKETING_AUDIENCE_ID',
  'MAILCHIMP_PROBELESEN_AUDIENCE_ID',
  'MAILCHIMP_PRODUKTINFOS_AUDIENCE_ID',
  'MAILCHIMP_INTEREST_PLEDGE',
  'MAILCHIMP_INTEREST_GRANTED_ACCESS',
  'MAILCHIMP_MARKETING_INTEREST_FREE_OFFERS_ONLY',
  'REGWALL_TRIAL_CAMPAIGN_ID',
])

const config = {
  MAILCHIMP_INTEREST_NEWSLETTER_DAILY:
    process.env.MAILCHIMP_INTEREST_NEWSLETTER_DAILY,
  MAILCHIMP_INTEREST_NEWSLETTER_WEEKLY:
    process.env.MAILCHIMP_INTEREST_NEWSLETTER_WEEKLY,
  MAILCHIMP_INTEREST_NEWSLETTER_PROJECTR:
    process.env.MAILCHIMP_INTEREST_NEWSLETTER_PROJECTR,
  MAILCHIMP_INTEREST_NEWSLETTER_CLIMATE:
    process.env.MAILCHIMP_INTEREST_NEWSLETTER_CLIMATE,
  MAILCHIMP_INTEREST_NEWSLETTER_WDWWW:
    process.env.MAILCHIMP_INTEREST_NEWSLETTER_WDWWW,
  MAILCHIMP_INTEREST_NEWSLETTER_ACCOMPLICE:
    process.env.MAILCHIMP_INTEREST_NEWSLETTER_ACCOMPLICE,
  MAILCHIMP_INTEREST_NEWSLETTER_SUNDAY:
    process.env.MAILCHIMP_INTEREST_NEWSLETTER_SUNDAY,
  MAILCHIMP_INTEREST_NEWSLETTER_BAB:
    process.env.MAILCHIMP_INTEREST_NEWSLETTER_BAB,
  MAILCHIMP_INTEREST_MEMBER: process.env.MAILCHIMP_INTEREST_MEMBER,
  MAILCHIMP_INTEREST_MEMBER_BENEFACTOR:
    process.env.MAILCHIMP_INTEREST_MEMBER_BENEFACTOR,
  MAILCHIMP_INTEREST_PAST_REGWALL_TRIAL:
    process.env.MAILCHIMP_INTEREST_PAST_REGWALL_TRIAL,
  MAILCHIMP_MAIN_LIST_ID: process.env.MAILCHIMP_MAIN_LIST_ID,
  MAILCHIMP_ONBOARDING_AUDIENCE_ID:
    process.env.MAILCHIMP_ONBOARDING_AUDIENCE_ID,
  MAILCHIMP_MARKETING_AUDIENCE_ID: process.env.MAILCHIMP_MARKETING_AUDIENCE_ID,
  MAILCHIMP_PROBELESEN_AUDIENCE_ID:
    process.env.MAILCHIMP_PROBELESEN_AUDIENCE_ID,
  MAILCHIMP_PRODUKTINFOS_AUDIENCE_ID:
    process.env.MAILCHIMP_PRODUKTINFOS_AUDIENCE_ID,
  MAILCHIMP_REGWALL_TRIAL_AUDIENCE_ID:
    process.env.MAILCHIMP_REGWALL_TRIAL_AUDIENCE_ID,
  MAILCHIMP_INTEREST_PLEDGE: process.env.MAILCHIMP_INTEREST_PLEDGE,
  MAILCHIMP_INTEREST_GRANTED_ACCESS:
    process.env.MAILCHIMP_INTEREST_GRANTED_ACCESS,
  MAILCHIMP_MARKETING_INTEREST_FREE_OFFERS_ONLY:
    process.env.MAILCHIMP_MARKETING_INTEREST_FREE_OFFERS_ONLY,
  REGWALL_TRIAL_CAMPAIGN_ID: process.env.REGWALL_TRIAL_CAMPAIGN_ID,
}

function assertEnvVariableExists(
  obj: any,
  keys: string | string[],
): asserts obj is Record<string, string> {
  if (Array.isArray(keys)) {
    for (const key of keys) {
      if (typeof obj[key] !== 'string') {
        throw new Error(`Config key ${key} is missing.`)
      }
    }
  } else {
    if (typeof obj[keys] !== 'string')
      throw new Error(`Config key ${keys} is missing.`)
  }
}

export function getConfig() {
  return config
}
