const {
  MAILCHIMP_INTEREST_NEWSLETTER_DAILY,
  MAILCHIMP_INTEREST_NEWSLETTER_WEEKLY,
  MAILCHIMP_INTEREST_NEWSLETTER_PROJECTR,
  MAILCHIMP_INTEREST_NEWSLETTER_CLIMATE,
  MAILCHIMP_INTEREST_NEWSLETTER_WDWWW,
  MAILCHIMP_INTEREST_NEWSLETTER_ACCOMPLICE,
  MAILCHIMP_INTEREST_MEMBER,
  MAILCHIMP_INTEREST_MEMBER_BENEFACTOR,
  MAILCHIMP_MAIN_LIST_ID,
  MAILCHIMP_ONBOARDING_AUDIENCE_ID,
  MAILCHIMP_MARKETING_AUDIENCE_ID,
  MAILCHIMP_PROBELESEN_AUDIENCE_ID,
  MAILCHIMP_PRODUKTINFOS_AUDIENCE_ID,
} = process.env

assertEnvVariableExists(
  MAILCHIMP_INTEREST_NEWSLETTER_DAILY,
  'MAILCHIMP_INTEREST_NEWSLETTER_DAILY',
)
assertEnvVariableExists(
  MAILCHIMP_INTEREST_NEWSLETTER_WEEKLY,
  'MAILCHIMP_INTEREST_NEWSLETTER_WEEKLY',
)
assertEnvVariableExists(
  MAILCHIMP_INTEREST_NEWSLETTER_PROJECTR,
  'MAILCHIMP_INTEREST_NEWSLETTER_PROJECTR',
)
assertEnvVariableExists(
  MAILCHIMP_INTEREST_NEWSLETTER_CLIMATE,
  'MAILCHIMP_INTEREST_NEWSLETTER_CLIMATE',
)
assertEnvVariableExists(
  MAILCHIMP_INTEREST_NEWSLETTER_WDWWW,
  'MAILCHIMP_INTEREST_NEWSLETTER_WDWWW',
)
assertEnvVariableExists(
  MAILCHIMP_INTEREST_NEWSLETTER_ACCOMPLICE,
  'MAILCHIMP_INTEREST_NEWSLETTER_ACCOMPLICE',
)

assertEnvVariableExists(MAILCHIMP_INTEREST_MEMBER, 'MAILCHIMP_INTEREST_MEMBER')
assertEnvVariableExists(
  MAILCHIMP_INTEREST_MEMBER_BENEFACTOR,
  'MAILCHIMP_INTEREST_MEMBER_BENEFACTOR',
)
assertEnvVariableExists(MAILCHIMP_MAIN_LIST_ID, 'MAILCHIMP_MAIN_LIST_ID')
assertEnvVariableExists(
  MAILCHIMP_ONBOARDING_AUDIENCE_ID,
  'MAILCHIMP_ONBOARDING_AUDIENCE_ID',
)
assertEnvVariableExists(
  MAILCHIMP_MARKETING_AUDIENCE_ID,
  'MAILCHIMP_MARKETING_AUDIENCE_ID',
)
assertEnvVariableExists(
  MAILCHIMP_PROBELESEN_AUDIENCE_ID,
  'MAILCHIMP_PROBELESEN_AUDIENCE_ID',
)
assertEnvVariableExists(
  MAILCHIMP_PRODUKTINFOS_AUDIENCE_ID,
  'MAILCHIMP_PRODUKTINFOS_AUDIENCE_ID',
)

export function assertEnvVariableExists(
  envVariable: string | undefined,
  envVariableName: string,
): asserts envVariable is string {
  if (!envVariable) {
    throw new Error(`Env-Variable ${envVariableName} is missing.`)
  }
}

export {
  MAILCHIMP_INTEREST_NEWSLETTER_DAILY,
  MAILCHIMP_INTEREST_NEWSLETTER_WEEKLY,
  MAILCHIMP_INTEREST_NEWSLETTER_PROJECTR,
  MAILCHIMP_INTEREST_NEWSLETTER_CLIMATE,
  MAILCHIMP_INTEREST_NEWSLETTER_WDWWW,
  MAILCHIMP_INTEREST_NEWSLETTER_ACCOMPLICE,
  MAILCHIMP_INTEREST_MEMBER,
  MAILCHIMP_INTEREST_MEMBER_BENEFACTOR,
  MAILCHIMP_MAIN_LIST_ID,
  MAILCHIMP_ONBOARDING_AUDIENCE_ID,
  MAILCHIMP_MARKETING_AUDIENCE_ID,
  MAILCHIMP_PROBELESEN_AUDIENCE_ID,
  MAILCHIMP_PRODUKTINFOS_AUDIENCE_ID,
}
