query ArticleDiscussion($path: String!) {
  document(path: $path) {
    id
    meta {
      template
      linkedDiscussion {
        id
        path
        closed
        comments(first: 0) {
          totalCount
        }
      }
      ownDiscussion {
        id
        path
        closed
        comments(first: 0) {
          totalCount
        }
      }
    }
  }
}
