query FollowableDocument($path: String!) {
  document(path: $path) {
    id
    content
    meta {
      title
      description
      path
      image
    }
    subscribedBy(onlyMe: true) {
      nodes {
        id
        active
        isEligibleForNotifications
      }
    }
  }
}
