query FollowableDocument($path: String!) {
  document(path: $path) {
    id
    content
    meta {
      title
      description
      path
    }
    subscribedBy(onlyMe: true) {
      nodes {
        ...SubscriptionFields
      }
    }
  }
}
