query Me {
  me {
    id
    username
    slug
    portrait
    name
    firstName
    lastName
    email
    initials
    roles
    isListed
    hasPublicProfile
    discussionNotificationChannels
    accessCampaigns {
      id
    }
    hasDormantMembership
    prolongBeforeDate
    activeMembership {
      id
      type {
        name
      }
      renew
      endDate
      graceEndDate
      canProlong
    }
    progressConsent: hasConsentedTo(name: "PROGRESS")
  }
}

query ProlitterisConsentQuery($prolitterisConsent: String!) {
  me {
    id
    prolitterisOptOut: hasConsentedTo(name: $prolitterisConsent)
  }
}

mutation RevokeProlitterisConsent($prolitterisConsent: String!) {
  revokeConsent(name: $prolitterisConsent) {
    id
    prolitterisOptOut: hasConsentedTo(name: $prolitterisConsent)
  }
}

mutation SubmitProlitterisConsent($prolitterisConsent: String!) {
  submitConsent(name: $prolitterisConsent) {
    id
    prolitterisOptOut: hasConsentedTo(name: $prolitterisConsent)
  }
}
