query Me {
  me {
    id
    username
    slug
    portrait
    name
    firstName
    lastName
    email
    initials
    roles
    isListed
    hasPublicProfile
    notificationChannels
    regwallTrialStatus
    accessCampaigns {
      id
    }
    accessGrants {
      id
      status
      endAt
    }
    hasDormantMembership
    prolongBeforeDate
    activeMembership {
      id
      type {
        name
      }
      renew
      endDate
      graceEndDate
      canProlong
    }
    activeMagazineSubscription {
      id
    }
    prolitterisOptOut: hasConsentedTo(name: "PROLITTERIS_OPT_OUT")
    progressOptOut: hasConsentedTo(name: "PROGRESS_OPT_OUT")
  }
  ipAllowlistAccess {
    name
  }
}
