query MyCallToActions {
  me {
    id
    callToActions {
      id
      beginAt
      endAt
      acknowledgedAt
      payload {
        ... on CallToActionBasicPayload {
          text
          linkHref
          linkLabel
          backgroundColor
          textColor
          illustration
        }

        ... on CallToActionComponentPayload {
          customComponent {
            key
            args
          }
        }
      }
    }
  }
}
