query NextReads($repoId: ID!, $path: String!) {
  nextReads(repoId: $repoId) {
    id
    documents {
      ...NextReadDocumentFields
    }
  }
  CURATED_READS: document(path: $path) {
    id
    meta {
      recommendations {
        nodes {
          ...NextReadDocumentFields
        }
      }
    }
  }
}
