query NextReadsBookmarks {
  me {
    id
    collectionItems(
      names: ["bookmarks"]
      first: 6
      progress: UNFINISHED
      uniqueDocuments: true
      lastDays: 300
    ) {
      nodes {
        id
        document {
          ...NextReadDocumentFields
        }
      }
    }
  }
}
