query OnboardingFormats($repoIds: [ID!]) {
  documents(repoIds: $repoIds) {
    nodes {
      id
      subscribedBy(onlyMe: true) {
        nodes {
          ...SubscriptionFields
        }
      }
    }
  }
}
