query OnboardingDocuments($repoIds: [ID!]) {
  documents(repoIds: $repoIds) {
    nodes {
      id
      repoId
      meta {
        title
        description
        path
        audioCover
      }
      subscribedBy(onlyMe: true) {
        nodes {
          ...SubscriptionFields
        }
      }
    }
  }
}
