query OnboardingFormats {
  sections: documents(template: "section") {
    nodes {
      id
      linkedDocuments {
        nodes {
          id
          meta {
            title
            audioCover
          }
          subscribedBy(onlyMe: true) {
            nodes {
              id
              active
              object {
                ... on User {
                  id
                  name
                }
                ... on Document {
                  id
                  meta {
                    title
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
