/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol

// Source: ../../../../../../studio/schema.json
export type AudioCover = {
  color?: string
  anchor?: string
  backgroundColor?: string
}

export type AudioCoverCrop = {
  x?: number
  y?: number
  width?: number
  height?: number
}

export type SanityImageAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
}

export type ArticlePreview = {
  _type: 'articlePreview'
  title?: string
  lead?: string
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
}

export type SeoImageBuilder = {
  _type: 'seoImageBuilder'
  text?: string
  fontSize?: number
  textPosition?: 'top' | 'center' | 'bottom'
  inverted?: boolean
  layout?: 'TEXT' | 'BACKGROUND_IMAGE' | 'LOGO'
  backgroundImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  logo?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
}

export type Seo = {
  _type: 'seo'
  title?: string
  description?: string
  useImageBuilder?: boolean
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  imageBuilder?: SeoImageBuilder
}

export type LegacyMeta = {
  _type: 'legacyMeta'
  template?: string
  audioCover?: AudioCover
  audioCoverCrop?: AudioCoverCrop
}

export type Mdast = {
  _type: 'mdast'
  content?: string
}

export type ContributorReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'contributor'
}

export type ArticleReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'article'
}

export type DiscussionReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'discussion'
}

export type ArticleCollectionReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'articleCollection'
}

export type NewsletterReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'newsletter'
}

export type PodcastReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'podcast'
}

export type PageThemeReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'pageTheme'
}

export type Article = {
  _id: string
  _type: 'article'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  description?: string
  autoSlug?: boolean
  slug: Slug
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  repoId?: string
  contributors?: Array<{
    kind?: string
    contributor?: ContributorReference
    _type: 'contributorEntry'
    _key: string
  }>
  articleRecommendations?: Array<
    {
      _key: string
    } & ArticleReference
  >
  discussion?: DiscussionReference
  inlineDiscussion?: boolean
  notificationTitle?: string
  articleCollection?: ArticleCollectionReference
  emailSubject?: string
  newsletter?: NewsletterReference
  suppressSyntheticReadAloud?: boolean
  syntheticVoice?:
    | 'huebsch-01150-rpblk'
    | 'huebsch-62964-rpblk'
    | 'huebsch-714-109-rpblk'
    | 'huebsch-82170-rpblk'
    | 'huebsch-285-169-rpblk'
    | 'huebsch-gen-female-e-rpblk'
  syntheticVoice2?:
    | 'huebsch-01150-rpblk'
    | 'huebsch-62964-rpblk'
    | 'huebsch-714-109-rpblk'
    | 'huebsch-82170-rpblk'
    | 'huebsch-285-169-rpblk'
    | 'huebsch-gen-female-e-rpblk'
  audioSourceMp3?: string
  podcast?: PodcastReference
  showTextProgress?: boolean
  readingAccess?: 'OPEN' | 'PAYNOTE' | 'REGWALL'
  theme?: PageThemeReference
  seo?: Seo
  mdast?: Mdast
  publikatorMeta?: LegacyMeta
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top: number
  bottom: number
  left: number
  right: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x: number
  y: number
  height: number
  width: number
}

export type PageTheme = {
  _id: string
  _type: 'pageTheme'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  kind?: string
  color?: Color
  darkMode?: boolean
}

export type Color = {
  _type: 'color'
  hex?: string
  alpha?: number
  hsl?: HslaColor
  hsv?: HsvaColor
  rgb?: RgbaColor
}

export type Podcast = {
  _id: string
  _type: 'podcast'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  appleUrl?: string
  spotifyUrl?: string
  podigeeSlug?: string
}

export type Newsletter = {
  _id: string
  _type: 'newsletter'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  replyTo?: string
  fromName?: string
  savedSegmentId?: number
}

export type ArticleCollection = {
  _id: string
  _type: 'articleCollection'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  description?: string
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  overview?: Array<
    | ({
        _key: string
      } & ArticleReference)
    | ({
        _key: string
      } & ArticlePreview)
  >
}

export type Discussion = {
  _id: string
  _type: 'discussion'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  discussionClosed?: boolean
  commentsMaxLength?: number
  commentsMinInterval?: number
  discussionAnonymity?: 'ALLOWED' | 'ENFORCED' | 'FORBIDDEN'
  tags?: Array<string>
  tagRequired?: boolean
}

export type Contributor = {
  _id: string
  _type: 'contributor'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  kind?: string
  userId?: string
}

export type Slug = {
  _type: 'slug'
  current: string
  source?: string
}

export type RgbaColor = {
  _type: 'rgbaColor'
  r?: number
  g?: number
  b?: number
  a?: number
}

export type HsvaColor = {
  _type: 'hsvaColor'
  h?: number
  s?: number
  v?: number
  a?: number
}

export type HslaColor = {
  _type: 'hslaColor'
  h?: number
  s?: number
  l?: number
  a?: number
}

export type Code = {
  _type: 'code'
  language?: string
  filename?: string
  code?: string
  highlightedLines?: Array<number>
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height: number
  width: number
  aspectRatio: number
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  thumbHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash: string
  extension: string
  mimeType: string
  size: number
  assetId: string
  uploadId?: string
  path: string
  url: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash: string
  extension: string
  mimeType: string
  size: number
  assetId: string
  uploadId?: string
  path: string
  url: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type AllSanitySchemaTypes =
  | AudioCover
  | AudioCoverCrop
  | SanityImageAssetReference
  | ArticlePreview
  | SeoImageBuilder
  | Seo
  | LegacyMeta
  | Mdast
  | ContributorReference
  | ArticleReference
  | DiscussionReference
  | ArticleCollectionReference
  | NewsletterReference
  | PodcastReference
  | PageThemeReference
  | Article
  | SanityImageCrop
  | SanityImageHotspot
  | PageTheme
  | Color
  | Podcast
  | Newsletter
  | ArticleCollection
  | Discussion
  | Contributor
  | Slug
  | RgbaColor
  | HsvaColor
  | HslaColor
  | Code
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint

// Source: src/app/(sanity)/articles/[...path]/page.tsx
// Variable: ARTICLE_QUERY
// Query: *[_type == "article" && slug.current == $slug][0]{    _id,    title,    description,    content,    contributors[]{      kind,      "name": contributor->title,    }  }
export type ARTICLE_QUERY_RESULT = {
  _id: string
  title: string | null
  description: string | null
  content: null
  contributors: Array<{
    kind: string | null
    name: string | null
  }> | null
} | null

// Source: src/app/(sanity)/articles/[...path]/page.tsx
// Variable: ARTICLE_SLUGS_QUERY
// Query: *[_type == "article" && defined(slug.current)]{    "slug": slug.current  }
export type ARTICLE_SLUGS_QUERY_RESULT = Array<{
  slug: string
}>

// Source: src/app/(sanity)/articles/page.tsx
// Variable: ARTICLES_QUERY
// Query: *[_type == "article" && defined(slug.current)][0...100]{    "slug": slug.current,    title  }
export type ARTICLES_QUERY_RESULT = Array<{
  slug: string
  title: string | null
}>

// Query TypeMap
import '@sanity/client'
declare module '@sanity/client' {
  interface SanityQueries {
    '*[_type == "article" && slug.current == $slug][0]{\n    _id,\n    title,\n    description,\n    content,\n    contributors[]{\n      kind,\n      "name": contributor->title,\n    }\n  }': ARTICLE_QUERY_RESULT
    '\n  *[_type == "article" && defined(slug.current)]{\n    "slug": slug.current\n  }': ARTICLE_SLUGS_QUERY_RESULT
    '\n  *[_type == "article" && defined(slug.current)][0...100]{\n    "slug": slug.current,\n    title\n  }': ARTICLES_QUERY_RESULT
  }
}
