/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol

// Source: ../../../studio/schema.json
export type AudioCover = {
  color?: string
  anchor?: string
  backgroundColor?: string
}

export type AudioCoverCrop = {
  x?: number
  y?: number
  width?: number
  height?: number
}

export type SanityImageAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
}

export type Image1 = {
  asset?: SanityImageAssetReference
  media?: unknown
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
  _type: 'image'
}

export type ImageDark = {
  asset?: SanityImageAssetReference
  media?: unknown
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
  _type: 'image'
}

export type ArticlePreview = {
  _type: 'articlePreview'
  title?: string
  lead?: string
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
}

export type Caption = {
  _type: 'caption'
  legend?: string
  credit?: string
}

export type ArticleReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'article'
}

export type ArticleCollectionReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'articleCollection'
}

export type InternalLink = {
  _type: 'internalLink'
  reference?: ArticleReference | ArticleCollectionReference
}

export type Link = {
  _type: 'link'
  href?: string
}

export type Variable = {
  _type: 'variable'
  name?: string
}

export type IfNot = {
  _type: 'ifNot'
  present?: string
  body?: Array<
    | {
        children?: Array<
          | {
              marks?: Array<string>
              text?: string
              _type: 'span'
              _key: string
            }
          | ({
              _key: string
            } & Variable)
        >
        style?: 'normal' | 'h3'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<
          | ({
              _key: string
            } & Link)
          | ({
              _key: string
            } & InternalLink)
        >
        level?: number
        _type: 'block'
        _key: string
      }
    | ({
        _key: string
      } & EditorialImage)
    | ({
        _key: string
      } & InfoBox)
    | ({
        _key: string
      } & BlockQuote)
    | ({
        _key: string
      } & Note)
    | ({
        _key: string
      } & InterviewAnswer)
    | ({
        _key: string
      } & CodeBlock)
    | ({
        _key: string
      } & Divider)
    | ({
        _key: string
      } & Chart)
    | ({
        _key: string
      } & EmbedVideo)
    | ({
        _key: string
      } & EmbedTwitter)
    | ({
        _key: string
      } & EmbedDataWrapper)
    | ({
        _key: string
      } & Html)
    | ({
        _key: string
      } & DynamicComponent)
    | ({
        _key: string
      } & Button)
  >
}

export type If = {
  _type: 'if'
  present?: string
  body?: Array<
    | {
        children?: Array<
          | {
              marks?: Array<string>
              text?: string
              _type: 'span'
              _key: string
            }
          | ({
              _key: string
            } & Variable)
        >
        style?: 'normal' | 'h3'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<
          | ({
              _key: string
            } & Link)
          | ({
              _key: string
            } & InternalLink)
        >
        level?: number
        _type: 'block'
        _key: string
      }
    | ({
        _key: string
      } & EditorialImage)
    | ({
        _key: string
      } & InfoBox)
    | ({
        _key: string
      } & BlockQuote)
    | ({
        _key: string
      } & Note)
    | ({
        _key: string
      } & InterviewAnswer)
    | ({
        _key: string
      } & CodeBlock)
    | ({
        _key: string
      } & Divider)
    | ({
        _key: string
      } & Chart)
    | ({
        _key: string
      } & EmbedVideo)
    | ({
        _key: string
      } & EmbedTwitter)
    | ({
        _key: string
      } & EmbedDataWrapper)
    | ({
        _key: string
      } & Html)
    | ({
        _key: string
      } & DynamicComponent)
    | ({
        _key: string
      } & Button)
  >
}

export type EmailOnly = {
  _type: 'emailOnly'
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?: 'normal' | 'h3'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<
          | ({
              _key: string
            } & Link)
          | ({
              _key: string
            } & InternalLink)
        >
        level?: number
        _type: 'block'
        _key: string
      }
    | ({
        _key: string
      } & Divider)
    | ({
        _key: string
      } & Html)
    | ({
        _key: string
      } & Button)
  >
}

export type WebOnly = {
  _type: 'webOnly'
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?: 'normal' | 'h3'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<
          | ({
              _key: string
            } & Link)
          | ({
              _key: string
            } & InternalLink)
        >
        level?: number
        _type: 'block'
        _key: string
      }
    | ({
        _key: string
      } & Divider)
    | ({
        _key: string
      } & Html)
    | ({
        _key: string
      } & Button)
  >
}

export type InterviewAnswer = {
  _type: 'interviewAnswer'
  body?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<
      | ({
          _key: string
        } & Link)
      | ({
          _key: string
        } & InternalLink)
    >
    level?: number
    _type: 'block'
    _key: string
  }>
}

export type Note = {
  _type: 'note'
  body?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<
      | ({
          _key: string
        } & Link)
      | ({
          _key: string
        } & InternalLink)
    >
    level?: number
    _type: 'block'
    _key: string
  }>
}

export type BlockQuote = {
  _type: 'blockQuote'
  body?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<
      | ({
          _key: string
        } & Link)
      | ({
          _key: string
        } & InternalLink)
    >
    level?: number
    _type: 'block'
    _key: string
  }>
  caption?: Caption
}

export type InfoBox = {
  _type: 'infoBox'
  title?: string
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    credit?: string
    _type: 'image'
  }
  body?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h3'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<
      | ({
          _key: string
        } & Link)
      | ({
          _key: string
        } & InternalLink)
    >
    level?: number
    _type: 'block'
    _key: string
  }>
}

export type Button = {
  _type: 'button'
  text?: string
  url?: string
}

export type DynamicComponent = {
  _type: 'dynamicComponent'
  src?: string
  props?: string
  autoHtml?: boolean
}

export type Html = {
  _type: 'html'
  html?: string
}

export type EmbedDataWrapper = {
  _type: 'embedDataWrapper'
  data?: string
}

export type EmbedTwitter = {
  _type: 'embedTwitter'
  data?: string
}

export type EmbedVideo = {
  _type: 'embedVideo'
  data?: string
}

export type Chart = {
  _type: 'chart'
  data?: string
}

export type Divider = {
  _type: 'divider'
  style?: string
}

export type CodeBlock = {
  _type: 'codeBlock'
  language?: string
  code?: string
}

export type ImageGroup = {
  _type: 'imageGroup'
  images?: Array<
    {
      _key: string
    } & GroupedEditorialImage
  >
  caption?: Caption
  size?: 'NARROW' | 'NORMAL' | 'LARGE'
}

export type GroupedEditorialImage = {
  _type: 'groupedEditorialImage'
  image?: Image1
  imageDark?: ImageDark
  alt?: string
  caption?: Caption
}

export type EditorialImage = {
  _type: 'editorialImage'
  image?: Image1
  imageDark?: ImageDark
  alt?: string
  caption?: Caption
  size?: 'NORMAL' | 'LARGE' | 'FULL'
}

export type SeoImageBuilder = {
  _type: 'seoImageBuilder'
  text?: string
  fontSize?: number
  textPosition?: 'top' | 'center' | 'bottom'
  inverted?: boolean
  layout?: 'TEXT' | 'BACKGROUND_IMAGE' | 'LOGO'
  backgroundImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  logo?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
}

export type Seo = {
  _type: 'seo'
  title?: string
  description?: string
  useImageBuilder?: boolean
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  imageBuilder?: SeoImageBuilder
}

export type LegacyMeta = {
  _type: 'legacyMeta'
  template?: string
  audioCover?: AudioCover
  audioCoverCrop?: AudioCoverCrop
}

export type Mdast = {
  _type: 'mdast'
  content?: string
}

export type ContributorReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'contributor'
}

export type DiscussionReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'discussion'
}

export type NewsletterReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'newsletter'
}

export type PodcastReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'podcast'
}

export type PageThemeReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'pageTheme'
}

export type Article = {
  _id: string
  _type: 'article'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  description?: string
  autoSlug?: boolean
  slug: Slug
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  repoId?: string
  content?: Array<
    | {
        children?: Array<
          | {
              marks?: Array<string>
              text?: string
              _type: 'span'
              _key: string
            }
          | {
              value?: string
              _type: 'softHyphen'
              _key: string
            }
          | {
              value?: string
              _type: 'nonBreakingSpace'
              _key: string
            }
          | ({
              _key: string
            } & Variable)
        >
        style?: 'normal' | 'h2' | 'h1' | 'h3' | 'h4' | 'h6'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<
          | ({
              _key: string
            } & Link)
          | ({
              _key: string
            } & InternalLink)
        >
        level?: number
        _type: 'block'
        _key: string
      }
    | ({
        _key: string
      } & EditorialImage)
    | ({
        _key: string
      } & ImageGroup)
    | ({
        _key: string
      } & InfoBox)
    | ({
        _key: string
      } & BlockQuote)
    | ({
        _key: string
      } & Note)
    | ({
        _key: string
      } & InterviewAnswer)
    | ({
        _key: string
      } & WebOnly)
    | ({
        _key: string
      } & EmailOnly)
    | ({
        _key: string
      } & If)
    | ({
        _key: string
      } & IfNot)
    | ({
        _key: string
      } & CodeBlock)
    | ({
        _key: string
      } & Divider)
    | ({
        _key: string
      } & Chart)
    | ({
        _key: string
      } & EmbedVideo)
    | ({
        _key: string
      } & EmbedTwitter)
    | ({
        _key: string
      } & EmbedDataWrapper)
    | ({
        _key: string
      } & Html)
    | ({
        _key: string
      } & DynamicComponent)
    | ({
        _key: string
      } & Button)
  >
  contributors?: Array<{
    kind?: string
    contributor?: ContributorReference
    _type: 'contributorEntry'
    _key: string
  }>
  articleRecommendations?: Array<
    {
      _key: string
    } & ArticleReference
  >
  discussion?: DiscussionReference
  inlineDiscussion?: boolean
  notificationTitle?: string
  articleCollection?: ArticleCollectionReference
  emailSubject?: string
  newsletter?: NewsletterReference
  suppressSyntheticReadAloud?: boolean
  syntheticVoice?:
    | 'huebsch-01150-rpblk'
    | 'huebsch-62964-rpblk'
    | 'huebsch-714-109-rpblk'
    | 'huebsch-82170-rpblk'
    | 'huebsch-285-169-rpblk'
    | 'huebsch-gen-female-e-rpblk'
  syntheticVoice2?:
    | 'huebsch-01150-rpblk'
    | 'huebsch-62964-rpblk'
    | 'huebsch-714-109-rpblk'
    | 'huebsch-82170-rpblk'
    | 'huebsch-285-169-rpblk'
    | 'huebsch-gen-female-e-rpblk'
  audioSourceMp3?: string
  podcast?: PodcastReference
  showTextProgress?: boolean
  readingAccess?: 'OPEN' | 'PAYNOTE' | 'REGWALL'
  theme?: PageThemeReference
  seo?: Seo
  mdast?: Mdast
  publikatorMeta?: LegacyMeta
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top: number
  bottom: number
  left: number
  right: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x: number
  y: number
  height: number
  width: number
}

export type PageTheme = {
  _id: string
  _type: 'pageTheme'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  kind?: 'EDITORIAL' | 'META'
  color?: Color
  darkMode?: boolean
}

export type Color = {
  _type: 'color'
  hex?: string
  alpha?: number
  hsl?: HslaColor
  hsv?: HsvaColor
  rgb?: RgbaColor
}

export type Podcast = {
  _id: string
  _type: 'podcast'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  appleUrl?: string
  spotifyUrl?: string
  podigeeSlug?: string
}

export type Newsletter = {
  _id: string
  _type: 'newsletter'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  description?: string
  frequency?: string
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  name: string
  replyTo?: string
  fromName?: string
  savedSegmentId?: number
}

export type ArticleCollection = {
  _id: string
  _type: 'articleCollection'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  description?: string
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  overview?: Array<
    | ({
        _key: string
      } & ArticleReference)
    | ({
        _key: string
      } & ArticlePreview)
  >
}

export type Discussion = {
  _id: string
  _type: 'discussion'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  discussionClosed?: boolean
  commentsMaxLength?: number
  commentsMinInterval?: number
  discussionAnonymity?: 'ALLOWED' | 'ENFORCED' | 'FORBIDDEN'
  tags?: Array<string>
  tagRequired?: boolean
}

export type Contributor = {
  _id: string
  _type: 'contributor'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  description?: string
  portrait?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  userId?: string
}

export type Slug = {
  _type: 'slug'
  current: string
  source?: string
}

export type RgbaColor = {
  _type: 'rgbaColor'
  r?: number
  g?: number
  b?: number
  a?: number
}

export type HsvaColor = {
  _type: 'hsvaColor'
  h?: number
  s?: number
  v?: number
  a?: number
}

export type HslaColor = {
  _type: 'hslaColor'
  h?: number
  s?: number
  l?: number
  a?: number
}

export type Code = {
  _type: 'code'
  language?: string
  filename?: string
  code?: string
  highlightedLines?: Array<number>
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height: number
  width: number
  aspectRatio: number
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  thumbHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash: string
  extension: string
  mimeType: string
  size: number
  assetId: string
  uploadId?: string
  path: string
  url: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash: string
  extension: string
  mimeType: string
  size: number
  assetId: string
  uploadId?: string
  path: string
  url: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type AllSanitySchemaTypes =
  | AudioCover
  | AudioCoverCrop
  | SanityImageAssetReference
  | Image1
  | ImageDark
  | ArticlePreview
  | Caption
  | ArticleReference
  | ArticleCollectionReference
  | InternalLink
  | Link
  | Variable
  | IfNot
  | If
  | EmailOnly
  | WebOnly
  | InterviewAnswer
  | Note
  | BlockQuote
  | InfoBox
  | Button
  | DynamicComponent
  | Html
  | EmbedDataWrapper
  | EmbedTwitter
  | EmbedVideo
  | Chart
  | Divider
  | CodeBlock
  | ImageGroup
  | GroupedEditorialImage
  | EditorialImage
  | SeoImageBuilder
  | Seo
  | LegacyMeta
  | Mdast
  | ContributorReference
  | DiscussionReference
  | NewsletterReference
  | PodcastReference
  | PageThemeReference
  | Article
  | SanityImageCrop
  | SanityImageHotspot
  | PageTheme
  | Color
  | Podcast
  | Newsletter
  | ArticleCollection
  | Discussion
  | Contributor
  | Slug
  | RgbaColor
  | HsvaColor
  | HslaColor
  | Code
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint

// Source: src/app/(sanity)/articles/[...path]/components/article-content.tsx
// Variable: ARTICLE_CONTENT_QUERY
// Query: *[_type == "article" && slug.current == $slug][0]{    _id,    content[]{        ...,        markDefs[]{          ...,          _type == "internalLink" => {            "slug": @.reference->slug          }        }    }  }
export type ARTICLE_CONTENT_QUERY_RESULT = {
  _id: string
  content: Array<
    | {
        children?: Array<
          | ({
              _key: string
            } & Variable)
          | {
              value?: string
              _type: 'nonBreakingSpace'
              _key: string
            }
          | {
              value?: string
              _type: 'softHyphen'
              _key: string
            }
          | {
              marks?: Array<string>
              text?: string
              _type: 'span'
              _key: string
            }
        >
        style?: 'h1' | 'h2' | 'h3' | 'h4' | 'h6' | 'normal'
        listItem?: 'bullet' | 'number'
        markDefs: Array<
          | {
              _key: string
              _type: 'internalLink'
              reference?: ArticleReference | ArticleCollectionReference
              slug: Slug | null
            }
          | {
              _key: string
              _type: 'link'
              href?: string
            }
        > | null
        level?: number
        _type: 'block'
        _key: string
      }
    | {
        _key: string
        _type: 'blockQuote'
        body?: Array<{
          children?: Array<{
            marks?: Array<string>
            text?: string
            _type: 'span'
            _key: string
          }>
          style?: 'normal'
          listItem?: 'bullet' | 'number'
          markDefs?: Array<
            | ({
                _key: string
              } & InternalLink)
            | ({
                _key: string
              } & Link)
          >
          level?: number
          _type: 'block'
          _key: string
        }>
        caption?: Caption
        markDefs: null
      }
    | {
        _key: string
        _type: 'button'
        text?: string
        url?: string
        markDefs: null
      }
    | {
        _key: string
        _type: 'chart'
        data?: string
        markDefs: null
      }
    | {
        _key: string
        _type: 'codeBlock'
        language?: string
        code?: string
        markDefs: null
      }
    | {
        _key: string
        _type: 'divider'
        style?: string
        markDefs: null
      }
    | {
        _key: string
        _type: 'dynamicComponent'
        src?: string
        props?: string
        autoHtml?: boolean
        markDefs: null
      }
    | {
        _key: string
        _type: 'editorialImage'
        image?: Image1
        imageDark?: ImageDark
        alt?: string
        caption?: Caption
        size?: 'FULL' | 'LARGE' | 'NORMAL'
        markDefs: null
      }
    | {
        _key: string
        _type: 'emailOnly'
        body?: Array<
          | ({
              _key: string
            } & Button)
          | ({
              _key: string
            } & Divider)
          | ({
              _key: string
            } & Html)
          | {
              children?: Array<{
                marks?: Array<string>
                text?: string
                _type: 'span'
                _key: string
              }>
              style?: 'h3' | 'normal'
              listItem?: 'bullet' | 'number'
              markDefs?: Array<
                | ({
                    _key: string
                  } & InternalLink)
                | ({
                    _key: string
                  } & Link)
              >
              level?: number
              _type: 'block'
              _key: string
            }
        >
        markDefs: null
      }
    | {
        _key: string
        _type: 'embedDataWrapper'
        data?: string
        markDefs: null
      }
    | {
        _key: string
        _type: 'embedTwitter'
        data?: string
        markDefs: null
      }
    | {
        _key: string
        _type: 'embedVideo'
        data?: string
        markDefs: null
      }
    | {
        _key: string
        _type: 'html'
        html?: string
        markDefs: null
      }
    | {
        _key: string
        _type: 'if'
        present?: string
        body?: Array<
          | ({
              _key: string
            } & BlockQuote)
          | ({
              _key: string
            } & Button)
          | ({
              _key: string
            } & Chart)
          | ({
              _key: string
            } & CodeBlock)
          | ({
              _key: string
            } & Divider)
          | ({
              _key: string
            } & DynamicComponent)
          | ({
              _key: string
            } & EditorialImage)
          | ({
              _key: string
            } & EmbedDataWrapper)
          | ({
              _key: string
            } & EmbedTwitter)
          | ({
              _key: string
            } & EmbedVideo)
          | ({
              _key: string
            } & Html)
          | ({
              _key: string
            } & InfoBox)
          | ({
              _key: string
            } & InterviewAnswer)
          | ({
              _key: string
            } & Note)
          | {
              children?: Array<
                | ({
                    _key: string
                  } & Variable)
                | {
                    marks?: Array<string>
                    text?: string
                    _type: 'span'
                    _key: string
                  }
              >
              style?: 'h3' | 'normal'
              listItem?: 'bullet' | 'number'
              markDefs?: Array<
                | ({
                    _key: string
                  } & InternalLink)
                | ({
                    _key: string
                  } & Link)
              >
              level?: number
              _type: 'block'
              _key: string
            }
        >
        markDefs: null
      }
    | {
        _key: string
        _type: 'ifNot'
        present?: string
        body?: Array<
          | ({
              _key: string
            } & BlockQuote)
          | ({
              _key: string
            } & Button)
          | ({
              _key: string
            } & Chart)
          | ({
              _key: string
            } & CodeBlock)
          | ({
              _key: string
            } & Divider)
          | ({
              _key: string
            } & DynamicComponent)
          | ({
              _key: string
            } & EditorialImage)
          | ({
              _key: string
            } & EmbedDataWrapper)
          | ({
              _key: string
            } & EmbedTwitter)
          | ({
              _key: string
            } & EmbedVideo)
          | ({
              _key: string
            } & Html)
          | ({
              _key: string
            } & InfoBox)
          | ({
              _key: string
            } & InterviewAnswer)
          | ({
              _key: string
            } & Note)
          | {
              children?: Array<
                | ({
                    _key: string
                  } & Variable)
                | {
                    marks?: Array<string>
                    text?: string
                    _type: 'span'
                    _key: string
                  }
              >
              style?: 'h3' | 'normal'
              listItem?: 'bullet' | 'number'
              markDefs?: Array<
                | ({
                    _key: string
                  } & InternalLink)
                | ({
                    _key: string
                  } & Link)
              >
              level?: number
              _type: 'block'
              _key: string
            }
        >
        markDefs: null
      }
    | {
        _key: string
        _type: 'imageGroup'
        images?: Array<
          {
            _key: string
          } & GroupedEditorialImage
        >
        caption?: Caption
        size?: 'LARGE' | 'NARROW' | 'NORMAL'
        markDefs: null
      }
    | {
        _key: string
        _type: 'infoBox'
        title?: string
        image?: {
          asset?: SanityImageAssetReference
          media?: unknown
          hotspot?: SanityImageHotspot
          crop?: SanityImageCrop
          credit?: string
          _type: 'image'
        }
        body?: Array<{
          children?: Array<{
            marks?: Array<string>
            text?: string
            _type: 'span'
            _key: string
          }>
          style?: 'h3' | 'normal'
          listItem?: 'bullet' | 'number'
          markDefs?: Array<
            | ({
                _key: string
              } & InternalLink)
            | ({
                _key: string
              } & Link)
          >
          level?: number
          _type: 'block'
          _key: string
        }>
        markDefs: null
      }
    | {
        _key: string
        _type: 'interviewAnswer'
        body?: Array<{
          children?: Array<{
            marks?: Array<string>
            text?: string
            _type: 'span'
            _key: string
          }>
          style?: 'normal'
          listItem?: 'bullet' | 'number'
          markDefs?: Array<
            | ({
                _key: string
              } & InternalLink)
            | ({
                _key: string
              } & Link)
          >
          level?: number
          _type: 'block'
          _key: string
        }>
        markDefs: null
      }
    | {
        _key: string
        _type: 'note'
        body?: Array<{
          children?: Array<{
            marks?: Array<string>
            text?: string
            _type: 'span'
            _key: string
          }>
          style?: 'normal'
          listItem?: 'bullet' | 'number'
          markDefs?: Array<
            | ({
                _key: string
              } & InternalLink)
            | ({
                _key: string
              } & Link)
          >
          level?: number
          _type: 'block'
          _key: string
        }>
        markDefs: null
      }
    | {
        _key: string
        _type: 'webOnly'
        body?: Array<
          | ({
              _key: string
            } & Button)
          | ({
              _key: string
            } & Divider)
          | ({
              _key: string
            } & Html)
          | {
              children?: Array<{
                marks?: Array<string>
                text?: string
                _type: 'span'
                _key: string
              }>
              style?: 'h3' | 'normal'
              listItem?: 'bullet' | 'number'
              markDefs?: Array<
                | ({
                    _key: string
                  } & InternalLink)
                | ({
                    _key: string
                  } & Link)
              >
              level?: number
              _type: 'block'
              _key: string
            }
        >
        markDefs: null
      }
  > | null
} | null

// Source: src/app/(sanity)/articles/[...path]/page.tsx
// Variable: ARTICLE_QUERY
// Query: *[_type == "article" && slug.current == $slug][0]{    _id,    title,    description,    articleCollection->{      title,      description,      image    },    newsletter->{      title,      description,      frequency,      image,      name,    },    theme->{      darkMode,      color    },    contributors[]{      _id,      kind,      "slug": contributor->userId,      "name": contributor->title,      "description": contributor->description,      "portrait": contributor->portrait    },    articleRecommendations[]->{      _id,      title,      description,      slug,      "collection": articleCollection->title,      theme->{        color      },      contributors[]{        kind,        "name": contributor->title,      }    }  }
export type ARTICLE_QUERY_RESULT = {
  _id: string
  title: string | null
  description: string | null
  articleCollection: {
    title: string
    description: string | null
    image: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
    } | null
  } | null
  newsletter: {
    title: string
    description: string | null
    frequency: string | null
    image: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
    } | null
    name: string
  } | null
  theme: {
    darkMode: boolean | null
    color: Color | null
  } | null
  contributors: Array<{
    _id: null
    kind: string | null
    slug: string | null
    name: string | null
    description: string | null
    portrait: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
    } | null
  }> | null
  articleRecommendations: Array<{
    _id: string
    title: string | null
    description: string | null
    slug: Slug
    collection: string | null
    theme: {
      color: Color | null
    } | null
    contributors: Array<{
      kind: string | null
      name: string | null
    }> | null
  }> | null
} | null

// Source: src/app/(sanity)/articles/page.tsx
// Variable: ARTICLES_QUERY
// Query: *[_type == "article" && defined(slug.current)][0...100]{    "slug": slug.current,    title  }
export type ARTICLES_QUERY_RESULT = Array<{
  slug: string
  title: string | null
}>

// Query TypeMap
import '@sanity/client'
declare module '@sanity/client' {
  interface SanityQueries {
    '*[_type == "article" && slug.current == $slug][0]{\n    _id,\n    content[]{\n        ...,\n        markDefs[]{\n          ...,\n          _type == "internalLink" => {\n            "slug": @.reference->slug\n          }\n        }\n    }\n  }': ARTICLE_CONTENT_QUERY_RESULT
    '*[_type == "article" && slug.current == $slug][0]{\n    _id,\n    title,\n    description,\n    articleCollection->{\n      title,\n      description,\n      image\n    },\n    newsletter->{\n      title,\n      description,\n      frequency,\n      image,\n      name,\n    },\n    theme->{\n      darkMode,\n      color\n    },\n    contributors[]{\n      _id,\n      kind,\n      "slug": contributor->userId,\n      "name": contributor->title,\n      "description": contributor->description,\n      "portrait": contributor->portrait\n    },\n    articleRecommendations[]->{\n      _id,\n      title,\n      description,\n      slug,\n      "collection": articleCollection->title,\n      theme->{\n        color\n      },\n      contributors[]{\n        kind,\n        "name": contributor->title,\n      }\n    }\n  }': ARTICLE_QUERY_RESULT
    '\n  *[_type == "article" && defined(slug.current)][0...100]{\n    "slug": slug.current,\n    title\n  }': ARTICLES_QUERY_RESULT
  }
}
