import {
  PdfIcon,
  DownloadIcon,
  AudioIcon,
  BookmarkIcon,
  BookmarkBorderIcon,
  SearchIcon,
  PlayIcon,
  PauseIcon,
  RewindIcon,
  CloseIcon,
  NewPageIcon,
  MoodIcon,
  ArrowDownIcon,
  ArrowUpIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  ReportIcon,
  EditIcon,
  UnpublishIcon,
  ReplyIcon,
  FeaturedIcon,
  MoreIcon,
  CheckIcon,
  GalleryIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  FullscreenIcon,
  FullscreenExitIcon,
  PodcastIcon,
  PlayCircleIcon,
  PauseCircleIcon,
  ReadingTimeIcon,
  MailIcon,
  MailOutlineIcon,
  PhonelinkIcon,
  LinkIcon,
  HighlightOffIcon,
  LaunchIcon,
  RssFeedIcon,
  ArrowDownwardIcon,
  ArrowForwardIcon,
  ArrowBackIcon,
  ExpandMoreIcon,
  ExpandLessIcon,
  DoneIcon,
  NotificationsActiveIcon,
  FollowIcon,
  NotificationIcon,
  NotificationsOffIcon,
  NotificationsNoneIcon,
  RotateLeftIcon,
  RevertIcon,
  ListIcon,
  UlIcon,
  OlIcon,
  FilterListIcon,
  AddIcon,
  RemoveIcon,
  RemoveCircleIcon,
  AccountBoxIcon,
  NoteAddIcon,
  VpnKeyIcon,
  LanguageIcon,
  FavoriteIcon,
  StarsIcon,
  TrendingFlatIcon,
  FolderIcon,
  DarkmodeIcon,
  ForwardIcon,
  ReplayIcon,
  CheckCircleIcon,
  LockIcon,
  TextFormatIcon,
  EtiquetteIcon,
  UnfoldLessIcon,
  UnfoldMoreIcon,
  BoldIcon,
  ItalicIcon,
  BreakIcon,
  ImageIcon,
  QuoteIcon,
  StrikeThrough,
  TitleIcon,
  CodeIcon,
  PunchlineIcon,
  ArticlePreviewIcon,
  FlyerTileIcon,
  FlyerTileMetaIcon,
  QuizIcon,
  DeleteIcon,
  MemoIcon,
  MicIcon,
  PlaylistAddIcon,
  PlaylistRemoveIcon,
  DragHandleIcon,
  SkipNextIcon,
  ArticleIcon,
  CopyToClippboardIcon,
  RadioCheckedIcon,
  RadioUncheckedIcon,
  TelegramIcon,
  SubIcon,
  SupIcon,
  InstagramIcon,
  BlockCodeIcon,
  ThreemaIcon,
  OpenSourceIcon,
  ParagraphIcon,
  TwitterIcon,
  YoutubeIcon,
  VimeoIcon,
  WhatsappIcon,
  GoogleIcon,
  AppleIcon,
  FacebookIcon,
  BlockQuoteIcon,
  ShareIcon,
  MarkdownIcon,
  BackIcon,
  DiscussionIcon,
  FontSizeIcon,
  CheckSmallIcon,
  ReadIcon,
  ChartIcon,
  SearchMenuIcon,
  SpotifyIcon,
  BoldSearchIcon,
} from '@project-r/styleguide'
import {
  IconPdf,
  IconDownload,
  IconVolumeUp,
  IconBookmark,
  IconBookmarkBorder,
  IconSearch,
  IconPlayArrow,
  IconPause,
  IconSkipPrevious,
  IconClose,
  IconOpenInNew,
  IconMood,
  IconKeyboardArrowDown,
  IconKeyboardArrowUp,
  IconKeyboardArrowLeft,
  IconKeyboardArrowRight,
  IconFlag,
  IconEdit,
  IconVisibilityOff,
  IconReply,
  IconStar,
  IconMoreVertical,
  IconCheck,
  IconFilter,
  IconChevronLeft,
  IconChevronRight,
  IconFullscreen,
  IconFullscreenExit,
  IconPodcasts,
  IconPlayCircleOutline,
  IconPauseCircleOutline,
  IconSchedule,
  IconMail,
  IconMailOutline,
  IconDevices,
  IconLink,
  IconCancelOutline,
  IconRssFeed,
  IconArrowDownward,
  IconArrowForward,
  IconArrowBack,
  IconExpandMore,
  IconExpandLess,
  IconDone,
  IconNotificationsActive,
  IconNotificationsOn,
  IconNotificationsOff,
  IconNotificationsNone,
  IconRotateLeftOutline,
  IconList,
  IconFormatListBulleted,
  IconFormatListNumbered,
  IconFilterList,
  IconAdd,
  IconRemoveOutline,
  IconDoNotDisturbOn,
  IconAccountBox,
  IconNoteAdd,
  IconVpnKey,
  IconLanguage,
  IconFavorite,
  IconStars,
  IconTrendingFlat,
  IconFolder,
  IconDarkMode,
  IconForward30,
  IconReplay10,
  IconLock,
  IconFormatColorText,
  IconSmsFailedOutline,
  IconUnfoldLess,
  IconUnfoldMore,
  IconFormatBold,
  IconFormatItalic,
  IconKeyboardReturn,
  IconImageOutline,
  IconFormatQuote,
  IconStrikethrough,
  IconTitle,
  IconCode,
  IconDragHandle,
  IconCallToActionOutline,
  IconViewQuilt,
  IconViewHeadline,
  IconQuizOutline,
  IconDeleteOutline,
  IconRateReview,
  IconMic,
  IconPlaylistAdd,
  IconPlayListAddCheck,
  IconSkipNext,
  IconSubject,
  IconContentCopy,
  IconRadioButtonChecked,
  IconRadioButtonUnchecked,
  IconSubscript,
  IconSuperscript,
  IconInstagram,
  IconTerminal,
  IconOpensource,
  IconParagraph,
  IconMarkdown,
  IconThreema,
  IconTelegram,
  IconCheckCircle,
  IconSpotify,
  IconShare,
  IconBack,
  IconCheckSmall,
  IconDiscussion,
  IconFontSize,
  IconChart,
  IconSearchMenu,
  IconSearchMenuBold,
} from '@republik/icons'
import { css } from 'glamor'

const TBDICON = () => <span style={{ fontSize: 10 }}>TODO</span>

const Icons: Record<string, React.ComponentType<{ size?: number | string }>[]> =
  {
    PDF: [PdfIcon, IconPdf],
    FileDownload: [DownloadIcon, IconDownload],
    Audio: [AudioIcon, IconVolumeUp],
    Bookmark: [BookmarkIcon, IconBookmark],
    BookmarkBorder: [BookmarkBorderIcon, IconBookmarkBorder],
    Search: [SearchIcon, IconSearch],
    Play: [PlayIcon, IconPlayArrow],
    Pause: [PauseIcon, IconPause],
    Rewind: [RewindIcon, IconSkipPrevious],
    Close: [CloseIcon, IconClose],
    NewPage: [NewPageIcon, IconOpenInNew],
    Mood: [MoodIcon, IconMood],
    ArrowDown: [ArrowDownIcon, IconKeyboardArrowDown],
    ArrowUp: [ArrowUpIcon, IconKeyboardArrowUp],
    ArrowLeft: [ArrowLeftIcon, IconKeyboardArrowLeft],
    ArrowRight: [ArrowRightIcon, IconKeyboardArrowRight],
    Report: [ReportIcon, IconFlag],
    Edit: [EditIcon, IconEdit],
    Unpublish: [UnpublishIcon, IconVisibilityOff],
    Reply: [ReplyIcon, IconReply],
    Featured: [FeaturedIcon, IconStar],
    More: [MoreIcon, IconMoreVertical],
    Check: [CheckIcon, IconCheck],
    Gallery: [GalleryIcon, IconFilter],
    ChevronLeft: [ChevronLeftIcon, IconChevronLeft],
    ChevronRight: [ChevronRightIcon, IconChevronRight],
    Fullscreen: [FullscreenIcon, IconFullscreen],
    FullscreenExit: [FullscreenExitIcon, IconFullscreenExit],
    Podcast: [PodcastIcon, IconPodcasts],
    PlayCircle: [PlayCircleIcon, IconPlayCircleOutline],
    PauseCircle: [PauseCircleIcon, IconPauseCircleOutline],
    ReadingTime: [ReadingTimeIcon, IconSchedule],
    Mail: [MailIcon, IconMail],
    MailOutline: [MailOutlineIcon, IconMailOutline],
    PhoneLink: [PhonelinkIcon, IconDevices],
    Link: [LinkIcon, IconLink],
    HighlightsOff: [HighlightOffIcon, IconCancelOutline],
    Launch: [LaunchIcon, IconOpenInNew],
    RssFeed: [RssFeedIcon, IconRssFeed],
    ArrowDownward: [ArrowDownwardIcon, IconArrowDownward],
    ArrowForwardIcon: [ArrowForwardIcon, IconArrowForward],
    ArrowBackIcon: [ArrowBackIcon, IconArrowBack],
    ExpandMoreIcon: [ExpandMoreIcon, IconExpandMore],
    ExpandLessIcon: [ExpandLessIcon, IconExpandLess],
    Done: [DoneIcon, IconDone],
    NotificationsActive: [NotificationsActiveIcon, IconNotificationsActive],
    Follow: [FollowIcon, IconNotificationsActive],
    NotificationsIcon: [NotificationIcon, IconNotificationsOn],
    NotificationsOffIcon: [NotificationsOffIcon, IconNotificationsOff],
    NotificationsNone: [NotificationsNoneIcon, IconNotificationsNone],
    RotateLeft: [RotateLeftIcon, IconRotateLeftOutline],
    RevertIcon: [RevertIcon, IconRotateLeftOutline],
    List: [ListIcon, IconList],
    UlIcon: [UlIcon, IconFormatListBulleted],
    OlIcon: [OlIcon, IconFormatListNumbered],
    FilterList: [FilterListIcon, IconFilterList],
    AddIcon: [AddIcon, IconAdd],
    RemoveIcon: [RemoveIcon, IconRemoveOutline],
    RemoveCircleIcon: [RemoveCircleIcon, IconDoNotDisturbOn],
    AccountBox: [AccountBoxIcon, IconAccountBox],
    NoteAdd: [NoteAddIcon, IconNoteAdd],
    Vpnkey: [VpnKeyIcon, IconVpnKey],
    Language: [LanguageIcon, IconLanguage],
    Favorite: [FavoriteIcon, IconFavorite],
    Stars: [StarsIcon, IconStars],
    TrendingFlat: [TrendingFlatIcon, IconTrendingFlat],
    Folder: [FolderIcon, IconFolder],
    DarkmodeIcon: [DarkmodeIcon, IconDarkMode],
    ForwardIcon: [ForwardIcon, IconForward30],
    ReplayIcon: [ReplayIcon, IconReplay10],
    CheckCircleIcon: [CheckCircleIcon, IconCheckCircle],
    LockIcon: [LockIcon, IconLock],
    TextFormatIcon: [TextFormatIcon, IconFormatColorText],
    EtiquetteIcon: [EtiquetteIcon, IconSmsFailedOutline],
    UnfoldLessIcon: [UnfoldLessIcon, IconUnfoldLess],
    UnfoldMoreIcon: [UnfoldMoreIcon, IconUnfoldMore],
    BoldIcon: [BoldIcon, IconFormatBold],
    ItalicIcon: [ItalicIcon, IconFormatItalic],
    BreakIcon: [BreakIcon, IconKeyboardReturn],
    ImageIcon: [ImageIcon, IconImageOutline],
    QuoteIcon: [QuoteIcon, IconFormatQuote],
    StrikeThrough: [StrikeThrough, IconStrikethrough],
    TitleIcon: [TitleIcon, IconTitle],
    CodeIcon: [CodeIcon, IconCode],
    PunchlineIcon: [PunchlineIcon, IconDragHandle],
    ArticlePreviewIcon: [ArticlePreviewIcon, IconCallToActionOutline],
    FlyerTileIcon: [FlyerTileIcon, IconViewQuilt],
    FlyerTileMetaIcon: [FlyerTileMetaIcon, IconViewHeadline],
    QuizIcon: [QuizIcon, IconQuizOutline],
    DeleteIcon: [DeleteIcon, IconDeleteOutline],
    MemoIcon: [MemoIcon, IconRateReview],
    MicIcon: [MicIcon, IconMic],
    PlayListAdd: [PlaylistAddIcon, IconPlaylistAdd],
    PlaylistRemoveIcon: [PlaylistRemoveIcon, IconPlayListAddCheck],
    DragHandleIcon: [DragHandleIcon, IconDragHandle],
    SkipNextIcon: [SkipNextIcon, IconSkipNext],
    ArticleIcon: [ArticleIcon, IconSubject],
    CopyToClippboardIcon: [CopyToClippboardIcon, IconContentCopy],
    RadioCheckedIcon: [RadioCheckedIcon, IconRadioButtonChecked],
    RadioUncheckedIcon: [RadioUncheckedIcon, IconRadioButtonUnchecked],
    TelegramIcon: [TelegramIcon, IconTelegram],
    SubIcon: [SubIcon, IconSubscript],
    SupIcon: [SupIcon, IconSuperscript],
    InstagramIcon: [InstagramIcon, IconInstagram],
    BlockCodeIcon: [BlockCodeIcon, IconTerminal],
    ThreemaIcon: [ThreemaIcon, IconThreema],
    OpenSourceIcon: [OpenSourceIcon, IconOpensource],
    ParagraphIcon: [ParagraphIcon, IconParagraph],
    ShareIcon: [ShareIcon, IconShare],
    MarkdownIcon: [MarkdownIcon, IconMarkdown],
    BackIcon: [BackIcon, IconBack],
    DiscussionIcon: [DiscussionIcon, IconDiscussion],
    FontSizeIcon: [FontSizeIcon, IconFontSize],
    CheckSmallIcon: [CheckSmallIcon, IconCheckSmall],
    ReadIcon: [ReadIcon, IconCheckCircle],
    ChartIcon: [ChartIcon, IconChart],
    SearchMenuIcon: [SearchMenuIcon, IconSearchMenu],
    SpotifyIcon: [SpotifyIcon, IconSpotify],
    BoldSearchIcon: [BoldSearchIcon, IconSearchMenuBold],
  }

function Page() {
  return (
    <table style={{ margin: '0 auto', padding: '2rem' }}>
      <thead {...table}>
        <tr>
          <th>Name</th>
          <th>Old</th>
          <th>New</th>
        </tr>
      </thead>
      <tbody>
        {Object.entries(Icons).map(([name, [Old, New]]) => (
          <tr key={name} {...row}>
            <td {...cell}>{name}</td>
            <td {...cell}>
              <Old size={32} />
            </td>
            <td {...cell}>
              <New size={32} />
            </td>
          </tr>
        ))}
      </tbody>
    </table>
  )
}

export default Page

const table = css({
  borderSpacing: '1rem',
})

const row = css({
  marginTop: '1rem',
  '&:first-child': {
    marginTop: 0,
  },
})

const cell = css({
  padding: '1rem',
  border: '1px solid #ccc',
})
