import {
  PdfIcon,
  DownloadIcon,
  AudioIcon,
  BookmarkIcon,
  BookmarkBorderIcon,
  SearchIcon,
  PlayIcon,
  PauseIcon,
  RewindIcon,
  CloseIcon,
  NewPageIcon,
  MoodIcon,
  ArrowDownIcon,
  ArrowUpIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  ReportIcon,
  EditIcon,
  UnpublishIcon,
  ReplyIcon,
  FeaturedIcon,
  MoreIcon,
  CheckIcon,
  GalleryIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  FullscreenIcon,
  FullscreenExitIcon,
  PodcastIcon,
  PlayCircleIcon,
  PauseCircleIcon,
  ReadingTimeIcon,
  MailIcon,
  MailOutlineIcon,
  PhonelinkIcon,
  LinkIcon,
  HighlightOffIcon,
  LaunchIcon,
  RssFeedIcon,
  ArrowDownwardIcon,
  ArrowForwardIcon,
  ArrowBackIcon,
  ExpandMoreIcon,
  ExpandLessIcon,
  DoneIcon,
  NotificationsActiveIcon,
  FollowIcon,
  NotificationIcon,
  NotificationsOffIcon,
  NotificationsNoneIcon,
  RotateLeftIcon,
  RevertIcon,
  ListIcon,
  UlIcon,
  OlIcon,
  FilterListIcon,
  AddIcon,
  RemoveIcon,
  RemoveCircleIcon,
  AccountBoxIcon,
  NoteAddIcon,
  VpnKeyIcon,
  LanguageIcon,
  FavoriteIcon,
  StarsIcon,
  TrendingFlatIcon,
  FolderIcon,
  DarkmodeIcon,
  ForwardIcon,
  ReplayIcon,
  CheckCircleIcon,
  LockIcon,
  TextFormatIcon,
  EtiquetteIcon,
  UnfoldLessIcon,
  UnfoldMoreIcon,
  BoldIcon,
  ItalicIcon,
  BreakIcon,
  ImageIcon,
  QuoteIcon,
  StrikeThrough,
  TitleIcon,
  CodeIcon,
  PunchlineIcon,
  ArticlePreviewIcon,
  FlyerTileIcon,
  FlyerTileMetaIcon,
  QuizIcon,
  DeleteIcon,
  MemoIcon,
  MicIcon,
  PlaylistAddIcon,
  PlaylistRemoveIcon,
  DragHandleIcon,
  SkipNextIcon,
  ArticleIcon,
  CopyToClippboardIcon,
  RadioCheckedIcon,
  RadioUncheckedIcon,
  TelegramIcon,
  SubIcon,
  SupIcon,
  InstagramIcon,
  BlockCodeIcon,
  ThreemaIcon,
  OpenSourceIcon,
  ParagraphIcon,
  TwitterIcon,
  YoutubeIcon,
  VimeoIcon,
  WhatsappIcon,
  GoogleIcon,
  AppleIcon,
  FacebookIcon,
  BlockQuoteIcon,
  ShareIcon,
  MarkdownIcon,
  BackIcon,
  DiscussionIcon,
  FontSizeIcon,
  CheckSmallIcon,
  ReadIcon,
  ChartIcon,
  SearchMenuIcon,
  SpotifyIcon,
  BoldSearchIcon,
} from '@project-r/styleguide'
import {
  IconPdf,
  IconDownload,
  IconBookmark,
  IconBookmarkBorder,
  IconSearch,
  IconPause,
  IconClose,
  IconOpenInNew,
  IconMood,
  IconKeyboardArrowDown,
  IconKeyboardArrowUp,
  IconKeyboardArrowLeft,
  IconKeyboardArrowRight,
  IconEdit,
  IconReply,
  IconMoreVertical,
  IconCheck,
  IconChevronLeft,
  IconChevronRight,
  IconFullscreen,
  IconFullscreenExit,
  IconPlayCircleOutline,
  IconReadTime,
  IconMail,
  IconMailOutline,
  IconDevices,
  IconLink,
  IconCancel,
  IconRssFeed,
  IconArrowDownward,
  IconArrowForward,
  IconArrowBack,
  IconExpandMore,
  IconExpandLess,
  IconDone,
  IconNotificationsActive,
  IconNotificationsOff,
  IconNotificationsNone,
  IconRotateLeftOutline,
  IconList,
  IconFilterList,
  IconAdd,
  IconRemoveOutline,
  IconAccountBox,
  IconNoteAdd,
  IconVpnKey,
  IconLanguage,
  IconFavorite,
  IconStars,
  IconTrendingFlat,
  IconFolder,
  IconDarkMode,
  IconLock,
  IconFormatColorText,
  IconUnfoldLess,
  IconUnfoldMore,
  IconFormatBold,
  IconFormatItalic,
  IconFormatQuote,
  IconTitle,
  IconCode,
  IconDragHandle,
  IconCallToActionOutline,
  IconDeleteOutline,
  IconMic,
  IconPlaylistAdd,
  IconPlaylistRemove,
  IconSkipNext,
  IconContentCopy,
  IconTerminal,
  IconOpensource,
  IconParagraph,
  IconMarkdown,
  IconLogoThreema,
  IconLogoTelegram,
  IconSpotify,
  IconShare,
  IconBack,
  IconCheckSmall,
  IconDiscussion,
  IconFontSize,
  IconChart,
  IconSearchMenu,
  IconSearchMenuBold,
  IconAudio,
  IconPlay,
  IconRewind,
  IconReport,
  IconUnpublish,
  IconFeatured,
  IconGallery,
  IconPodcast,
  IconPauseCircle,
  IconNotifications,
  IconUnorderedList,
  IconOrderedList,
  IconRemoveCircle,
  IconForward,
  IconReplay,
  IconEtiquette,
  IconBreak,
  IconImage,
  IconFormatStrikethrough,
  IconFlyerTile,
  IconFollow,
  IconFlyerTileMeta,
  IconQuiz,
  IconMemo,
  IconArticle,
  IconRadioChecked,
  IconRadioUnchecked,
  IconFormatSubscript,
  IconFormatSuperscript,
  IconInstagram,
  IconRead,
  IconCheckCircle,
  IconCallReceived,
  IconArrowDropDown,
  IconArrowDropUp,
  IconArrowLeft,
  IconArrowRight,
  IconArrowUpward,
  IconCallSplit,
  IconContentCopyOutline,
  IconDesktopMac,
  IconError,
  IconErrorOutline,
  IconFilterIcon,
  IconFormatBlockquote,
  IconGears,
  IconGrade,
  IconHearing,
  IconHome,
  IconInfoOutline,
  IconLaptopMac,
  IconLens,
  IconLightMode,
  IconLockOpen,
  IconLogoApple,
  IconLogoFacebook,
  IconLogoGoogle,
  IconLogoTwitter,
  IconLogoVimeo,
  IconLogoWhatsApp,
  IconLogoYouTube,
  IconMoreHorizontal,
  IconPerson,
  IconPersonOutline,
  IconPhoneIPhone,
  IconPublic,
  IconRemove,
  IconPunchline,
  IconSubdirectoryArrowLeft,
  IconSubdirectoryArrowRight,
  IconTabletMac,
  IconTag,
  IconVerticalAlignBottom,
  IconVerticalAlignTop,
  IconWarning,
  IconWifiOff,
  IconWrapText,
} from '@republik/icons'
import { css } from 'glamor'

const TBDICON = () => (
  <span style={{ fontSize: 10, textAlign: 'center' }}>NONE</span>
)

const Icons: Record<string, React.ComponentType<{ size?: number | string }>[]> =
  {
    PDF: [PdfIcon, IconPdf],
    FileDownload: [DownloadIcon, IconDownload],
    Audio: [AudioIcon, IconAudio],
    Bookmark: [BookmarkIcon, IconBookmark],
    BookmarkBorder: [BookmarkBorderIcon, IconBookmarkBorder],
    Search: [SearchIcon, IconSearch],
    Play: [PlayIcon, IconPlay],
    Pause: [PauseIcon, IconPause],
    Rewind: [RewindIcon, IconRewind],
    Close: [CloseIcon, IconClose],
    NewPage: [NewPageIcon, IconOpenInNew],
    Mood: [MoodIcon, IconMood],
    ArrowDown: [ArrowDownIcon, IconKeyboardArrowDown],
    ArrowUp: [ArrowUpIcon, IconKeyboardArrowUp],
    ArrowLeft: [ArrowLeftIcon, IconKeyboardArrowLeft],
    ArrowRight: [ArrowRightIcon, IconKeyboardArrowRight],
    Report: [ReportIcon, IconReport],
    Edit: [EditIcon, IconEdit],
    Unpublish: [UnpublishIcon, IconUnpublish],
    Reply: [ReplyIcon, IconReply],
    Featured: [FeaturedIcon, IconFeatured],
    More: [MoreIcon, IconMoreVertical],
    Check: [CheckIcon, IconCheck],
    Gallery: [GalleryIcon, IconGallery],
    ChevronLeft: [ChevronLeftIcon, IconChevronLeft],
    ChevronRight: [ChevronRightIcon, IconChevronRight],
    Fullscreen: [FullscreenIcon, IconFullscreen],
    FullscreenExit: [FullscreenExitIcon, IconFullscreenExit],
    Podcast: [PodcastIcon, IconPodcast],
    PlayCircle: [PlayCircleIcon, IconPlayCircleOutline],
    PauseCircle: [PauseCircleIcon, IconPauseCircle],
    ReadingTime: [ReadingTimeIcon, IconReadTime],
    Mail: [MailIcon, IconMail],
    MailOutline: [MailOutlineIcon, IconMailOutline],
    PhoneLink: [PhonelinkIcon, IconDevices],
    Link: [LinkIcon, IconLink],
    HighlightsOff: [HighlightOffIcon, IconCancel],
    Launch: [LaunchIcon, IconOpenInNew],
    RssFeed: [RssFeedIcon, IconRssFeed],
    ArrowDownward: [ArrowDownwardIcon, IconArrowDownward],
    ArrowForwardIcon: [ArrowForwardIcon, IconArrowForward],
    ArrowBackIcon: [ArrowBackIcon, IconArrowBack],
    ExpandMoreIcon: [ExpandMoreIcon, IconExpandMore],
    ExpandLessIcon: [ExpandLessIcon, IconExpandLess],
    Done: [DoneIcon, IconDone],
    NotificationsActive: [NotificationsActiveIcon, IconNotificationsActive],
    Follow: [FollowIcon, IconFollow],
    NotificationsIcon: [NotificationIcon, IconNotifications],
    NotificationsOffIcon: [NotificationsOffIcon, IconNotificationsOff],
    NotificationsNone: [NotificationsNoneIcon, IconNotificationsNone],
    RotateLeft: [RotateLeftIcon, IconRotateLeftOutline],
    RevertIcon: [RevertIcon, IconRotateLeftOutline],
    List: [ListIcon, IconList],
    UlIcon: [UlIcon, IconUnorderedList],
    OlIcon: [OlIcon, IconOrderedList],
    FilterList: [FilterListIcon, IconFilterList],
    AddIcon: [AddIcon, IconAdd],
    RemoveIcon: [RemoveIcon, IconRemoveOutline],
    RemoveCircleIcon: [RemoveCircleIcon, IconRemoveCircle],
    AccountBox: [AccountBoxIcon, IconAccountBox],
    NoteAdd: [NoteAddIcon, IconNoteAdd],
    Vpnkey: [VpnKeyIcon, IconVpnKey],
    Language: [LanguageIcon, IconLanguage],
    Favorite: [FavoriteIcon, IconFavorite],
    Stars: [StarsIcon, IconStars],
    TrendingFlat: [TrendingFlatIcon, IconTrendingFlat],
    Folder: [FolderIcon, IconFolder],
    DarkmodeIcon: [DarkmodeIcon, IconDarkMode],
    ForwardIcon: [ForwardIcon, IconForward],
    ReplayIcon: [ReplayIcon, IconReplay],
    CheckCircleIcon: [CheckCircleIcon, IconCheckCircle],
    LockIcon: [LockIcon, IconLock],
    TextFormatIcon: [TextFormatIcon, IconFormatColorText],
    EtiquetteIcon: [EtiquetteIcon, IconEtiquette],
    UnfoldLessIcon: [UnfoldLessIcon, IconUnfoldLess],
    UnfoldMoreIcon: [UnfoldMoreIcon, IconUnfoldMore],
    BoldIcon: [BoldIcon, IconFormatBold],
    ItalicIcon: [ItalicIcon, IconFormatItalic],
    BreakIcon: [BreakIcon, IconBreak],
    ImageIcon: [ImageIcon, IconImage],
    QuoteIcon: [QuoteIcon, IconFormatQuote],
    StrikeThrough: [StrikeThrough, IconFormatStrikethrough],
    TitleIcon: [TitleIcon, IconTitle],
    CodeIcon: [CodeIcon, IconCode],
    PunchlineIcon: [PunchlineIcon, IconDragHandle],
    ArticlePreviewIcon: [ArticlePreviewIcon, IconCallToActionOutline],
    FlyerTileIcon: [FlyerTileIcon, IconFlyerTile],
    FlyerTileMetaIcon: [FlyerTileMetaIcon, IconFlyerTileMeta],
    QuizIcon: [QuizIcon, IconQuiz],
    DeleteIcon: [DeleteIcon, IconDeleteOutline],
    MemoIcon: [MemoIcon, IconMemo],
    MicIcon: [MicIcon, IconMic],
    PlayListAdd: [PlaylistAddIcon, IconPlaylistAdd],
    PlaylistRemoveIcon: [PlaylistRemoveIcon, IconPlaylistRemove],
    DragHandleIcon: [DragHandleIcon, IconDragHandle],
    SkipNextIcon: [SkipNextIcon, IconSkipNext],
    ArticleIcon: [ArticleIcon, IconArticle],
    CopyToClippboardIcon: [CopyToClippboardIcon, IconContentCopy],
    RadioCheckedIcon: [RadioCheckedIcon, IconRadioChecked],
    RadioUncheckedIcon: [RadioUncheckedIcon, IconRadioUnchecked],
    TelegramIcon: [TelegramIcon, IconLogoTelegram],
    SubIcon: [SubIcon, IconFormatSubscript],
    SupIcon: [SupIcon, IconFormatSuperscript],
    InstagramIcon: [InstagramIcon, IconInstagram],
    BlockCodeIcon: [BlockCodeIcon, IconTerminal],
    ThreemaIcon: [ThreemaIcon, IconLogoThreema],
    OpenSourceIcon: [OpenSourceIcon, IconOpensource],
    ParagraphIcon: [ParagraphIcon, IconParagraph],
    TwitterIcon: [TwitterIcon, IconLogoTwitter],
    YoutubeIcon: [YoutubeIcon, IconLogoYouTube],
    VimeoIcon: [VimeoIcon, IconLogoVimeo],
    WhatsappIcon: [WhatsappIcon, IconLogoWhatsApp],
    GoogleIcon: [GoogleIcon, IconLogoGoogle],
    AppleIcon: [AppleIcon, IconLogoApple],
    FacebookIcon: [FacebookIcon, IconLogoFacebook],
    ShareIcon: [ShareIcon, IconShare],
    MarkdownIcon: [MarkdownIcon, IconMarkdown],
    BackIcon: [BackIcon, IconBack],
    DiscussionIcon: [DiscussionIcon, IconDiscussion],
    FontSizeIcon: [FontSizeIcon, IconFontSize],
    CheckSmallIcon: [CheckSmallIcon, IconCheckSmall],
    ReadIcon: [ReadIcon, IconRead],
    ChartIcon: [ChartIcon, IconChart],
    SearchMenuIcon: [SearchMenuIcon, IconSearchMenu],
    SpotifyIcon: [SpotifyIcon, IconSpotify],
    BoldSearchIcon: [BoldSearchIcon, IconSearchMenuBold],
    BlockQuoteIcon: [BlockQuoteIcon, IconFormatBlockquote],
    IconCallReceived: [TBDICON, IconCallReceived],
    IconArrowDropDown: [TBDICON, IconArrowDropDown],
    IconArrowDropUp: [TBDICON, IconArrowDropUp],
    IconArrowLeft: [TBDICON, IconArrowLeft],
    IconArrowRight: [TBDICON, IconArrowRight],
    IconArrowUpward: [TBDICON, IconArrowUpward],
    IconCallSplit: [TBDICON, IconCallSplit],
    IconContentCopyOutline: [TBDICON, IconContentCopyOutline],
    IconDesktopMac: [TBDICON, IconDesktopMac],
    IconError: [TBDICON, IconError],
    IconErrorOutline: [TBDICON, IconErrorOutline],
    IconFilterIcon: [TBDICON, IconFilterIcon],
    IconFormatBlockquote: [TBDICON, IconFormatBlockquote],
    IconGears: [TBDICON, IconGears],
    IconGrade: [TBDICON, IconGrade],
    IconHearing: [TBDICON, IconHearing],
    IconHome: [TBDICON, IconHome],
    IconInfoOutline: [TBDICON, IconInfoOutline],
    IconLaptopMac: [TBDICON, IconLaptopMac],
    IconLens: [TBDICON, IconLens],
    IconLightMode: [TBDICON, IconLightMode],
    IconLockOpen: [TBDICON, IconLockOpen],
    IconMoreHorizontal: [TBDICON, IconMoreHorizontal],
    IconPerson: [TBDICON, IconPerson],
    IconPersonOutline: [TBDICON, IconPersonOutline],
    IconPhoneIPhone: [TBDICON, IconPhoneIPhone],
    IconPublic: [TBDICON, IconPublic],
    IconRemove: [TBDICON, IconRemove],
    IconPunchline: [TBDICON, IconPunchline],
    IconSubdirectoryArrowLeft: [TBDICON, IconSubdirectoryArrowLeft],
    IconSubdirectoryArrowRight: [TBDICON, IconSubdirectoryArrowRight],
    IconTabletMac: [TBDICON, IconTabletMac],
    IconTag: [TBDICON, IconTag],
    IconVerticalAlignBottom: [TBDICON, IconVerticalAlignBottom],
    IconVerticalAlignTop: [TBDICON, IconVerticalAlignTop],
    IconWarning: [TBDICON, IconWarning],
    IconWifiOff: [TBDICON, IconWifiOff],
    IconWrapText: [TBDICON, IconWrapText],
  }

function Page() {
  return (
    <table style={{ margin: '0 auto', padding: '2rem' }}>
      <thead {...table}>
        <tr>
          <th>Name</th>
          <th>Old</th>
          <th>New</th>
        </tr>
      </thead>
      <tbody>
        {Object.entries(Icons).map(([name, [Old, New]], i) => (
          <tr key={name} {...row}>
            <td {...cell}>
              {i + 1}. {name}
            </td>
            <td {...cell}>
              <Old size={32} />
            </td>
            <td {...cell}>
              <New size={32} />
            </td>
          </tr>
        ))}
      </tbody>
    </table>
  )
}

export default Page

const table = css({
  borderSpacing: '1rem',
})

const row = css({
  marginTop: '1rem',
  '&:first-child': {
    marginTop: 0,
  },
})

const cell = css({
  padding: '1rem',
  border: '1px solid #ccc',
})
