query Contributor($id: ID, $slug: String) {
  contributor(id: $id, slug: $slug) {
    id
    name
    slug
    shortBio
    image
    prolitterisId
    prolitterisFirstname
    prolitterisLastname
    bio
    gender
    userId
    createdAt
    updatedAt
  }
}

query Contributors($first: Int, $orderBy: ContributorOrderBy) {
  contributors(first: $first, orderBy: $orderBy) {
    totalCount
    pageInfo {
      hasNextPage
      endCursor
    }
    nodes {
      id
      name
      slug
      shortBio
      image
      prolitterisId
      prolitterisFirstname
      prolitterisLastname
      bio
      gender
      userId
      createdAt
      updatedAt
    }
  }
}
