query UserMagazineSubscriptions($userId: ID!) {
  user(id: $userId) {
    magazineSubscriptions {
      id
      company
      type
      status
      stripeId
      currentPeriodStart
      currentPeriodEnd
      createdAt
      updatedAt
      endedAt
      canceledAt
      renewsAtPrice
    }
  }
}
