query UserMagazineSubscriptions($userId: ID!) {
  user(id: $userId) {
    magazineSubscriptions {
      id
      company
      type
      status
      stripeId
      currentPeriodStart
      currentPeriodEnd
      createdAt
      updatedAt
      endedAt
      cancelAt
      canceledAt
      renewsAtPrice

      donation {
        amount
      }

      upgrade {
        id
        createdAt
        scheduledStart
        subscriptionType
        billingDetails {
          total
          donation {
            amount
          }
        }
      }
    }
  }
}
