const ENV =
  typeof window !== 'undefined' && window.__NEXT_DATA__
    ? window.__NEXT_DATA__.env
    : process.env

export const PUBLIC_BASE_URL = ENV.PUBLIC_BASE_URL

export const LOCALE = ENV.LOCALE
export const GITHUB_ORG = ENV.GITHUB_ORG
export const API_URL = ENV.API_URL
export const API_UNCOMMITTED_CHANGES_URL = ENV.API_UNCOMMITTED_CHANGES_URL
export const API_WS_URL = ENV.API_WS_URL
export const API_AUTHORIZATION_HEADER = ENV.API_AUTHORIZATION_HEADER
export const FRONTEND_BASE_URL = ENV.FRONTEND_BASE_URL

export const PIWIK_URL_BASE = ENV.PIWIK_URL_BASE
export const PIWIK_SITE_ID = ENV.PIWIK_SITE_ID

export const TEMPLATES = ENV.TEMPLATES
export const REPO_PREFIX = ENV.REPO_PREFIX

export const SG_COLORS = ENV.SG_COLORS
export const SG_FONT_STYLES = ENV.SG_FONT_STYLES
export const SG_FONT_FACES = ENV.SG_FONT_FACES
export const SG_LOGO_PATH = ENV.SG_LOGO_PATH
export const SG_LOGO_VIEWBOX = ENV.SG_LOGO_VIEWBOX
export const SG_BRAND_MARK_PATH = ENV.SG_BRAND_MARK_PATH
export const SG_BRAND_MARK_VIEWBOX = ENV.SG_BRAND_MARK_VIEWBOX
export const SG_DYNAMIC_COMPONENT_BASE_URLS = ENV.SG_DYNAMIC_COMPONENT_BASE_URLS

export const UNCOMMITTED_CHANGES_POLL_INTERVAL_MS =
  +ENV.UNCOMMITTED_CHANGES_POLL_INTERVAL_MS || 0
