query Cockpit {
  cockpit {
    id
    intro {
      value
    }
    membershipsCountChart {
      value
    }
    membershipsChangeChart {
      value
    }
    ourCommunity {
      value
    }
    activeMembers {
      value
    }
  }
}
