query Events($today: DateTime!) {
  events: allEvents(
    filter: {
      AND: [
        { unlisted: { eq: false } }
        { OR: [{ startAt: { gte: $today } }, { endAt: { gte: $today } }] }
      ]
    }
    orderBy: startAt_ASC
  ) {
    ...EventRecordFields
  }
  pastEvents: allEvents(
    filter: {
      AND: [
        { unlisted: { eq: false } }
        {
          AND: [
            { startAt: { lt: $today } }
            { OR: [{ endAt: { lt: $today } }, { endAt: { exists: false } }] }
          ]
        }
      ]
    }
    orderBy: startAt_DESC
  ) {
    ...EventRecordFields
  }
}
