query EventMeta($slug: String) {
  event(filter: { slug: { eq: $slug } }) {
    id
    title
    location
    locationLink
    startAt
    endAt
    description {
      value
    }
    signUpLink
    membersOnly
    fullyBooked
    ticketPrice
    seo {
      title
      description
      image {
        url(imgixParams: { w: "1500" })
      }
    }
  }
}
