query MarketingLandingPageCMS {
  marketingLandingPage {
    id
    reasons {
      id
      title
      description
    }
    formats {
      imageDark {
        responsiveImage(imgixParams: { w: 160 }) {
          src
        }
      }
      imageBright {
        responsiveImage(imgixParams: { w: 160 }) {
          src
        }
      }
      title
      description
      color {
        hex
      }
    }
    sectionTeamTitle
    sectionTeamDescription
    sectionDialogTitle
    sectionDialogDescription
    sectionFormatsTitle
    sectionFormatsDescription
  }
  employees: allEmployees(
    first: 15
    filter: {AND: [{employee: {eq: true}}, {pitch: {isPresent: true}}]}
  ) {
    ...EmployeeRecordFields
  }
}
