query Paynotes {
  paynoteConfig {
    id
    paynotes {
      id
      title
      message {
        value
      }
      author {
        name
        description
        portrait {
          url(imgixParams: { ar: "1:1", fit: crop, w: 160, h: 160 })
        }
      }
    }
    miniPaynotes {
      id
      message
    }
  }
}
