query Paynotes {
  paynotes: allPaynotes {
    id
    title
    message {
      value
    }
    analyticsId
    author {
      name
      description
      portrait {
        url(imgixParams: { ar: "1:1", fit: crop, w: 160, h: 160 })
      }
    }
  }
}
