-- migrate up here: CREATE TABLE...
CREATE INDEX "postfinancePayments_payment_key" ON "public"."postfinancePayments"("buchungsdatum","valuta","avisierungstext","gutschrift");
ALTER TABLE "public"."postfinancePayments" DROP CONSTRAINT "postfinancePayments_buchungsdatum_valuta_avisierungstext_gu_key";
