fragment AudioQueueItemRef on AudioQueueItemRef {
  id
  sequence
  mediaId
  repoId
  sanityId
  userProgress {
    id
    secs
  }
}

query AudioQueueQuery {
  userAudioQueue {
    ...AudioQueueItemRef
  }
}

mutation AddAudioQueueItemRef($entity: AudioQueueEntityInput!, $sequence: Int) {
  audioQueueItems: addAudioQueueItemRef(entity: $entity, sequence: $sequence) {
    ...AudioQueueItemRef
  }
}

mutation MoveAudioQueueItem($id: ID!, $sequence: Int!) {
  audioQueueItems: moveAudioQueueItemRef(id: $id, sequence: $sequence) {
    id
    sequence
  }
}

mutation RemoveAudioQueueItem($id: ID!) {
  audioQueueItems: removeAudioQueueItemRef(id: $id) {
    id
  }
}

mutation ClearAudioQueue {
  audioQueueItems: clearAudioQueueRefs {
    id
  }
}

mutation ReorderAudioQueue($ids: [ID!]!) {
  audioQueueItems: reorderAudioQueueRefs(ids: $ids) {
    id
    sequence
  }
}
