fragment EmployeeRecordFields on EmployeeRecord {
  employee
  name
  gender
  greeting
  group
  pitch
  promotedAuthor
  subgroup
  title
  userId
  famous
  _updatedAt
  profile {
    url(imgixParams: { sat: -100, w: 384, h: 384, fit: crop })
  }
}
