fragment EventRecordFields on EventRecord {
  id
  title
  slug
  description {
    value
  }
  membersOnly
  nonMemberCta {
    value
  }
  fullyBooked
  ticketPrice
  signUpLink
  location
  locationLink
  startAt
  endAt
  _updatedAt
  _status
}
