name: e2e tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  docker-containers:
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - uses: actions/checkout@v2

      - name: Cache Docker images
        id: docker-image-cache
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
          path: |
            /var/lib/docker/images

      - name: Download Docker images
        if: steps.docker-image-cache.cache-hit != 'true'
        run: docker compose pull

      - name: Run docker compose
        run: docker-compose up -d

  e2e-tests:
    runs-on: ubuntu-latest
    needs: [ docker-containers ]
    env:
      CI: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: yarn

      - name: Cache Playwright browsers
        id: playwright-browser-cache
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
          path: |
            ~/.cache/ms-playwright

      - name: Install Playwright browsers
        if: steps.playwright-browser-cache.cache-hit != 'true'
        run: npx playwright install --with-deps

      - name: Run your tests
        run: yarn test:e2e

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: playwright-results
          path: ./apps/*/e2e/artifacts


