name: e2e tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  e2e-tests:
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: yarn

      - name: Cache Playwright browsers
        id: playwright-browser-cache
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
          path: |
            ~/.cache/ms-playwright

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run your tests
        run: yarn test:e2e

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: playwright-results
          path: ./apps/*/e2e/artifacts