export const API_BASE_URL = process.env.NEXT_PUBLIC_API_URL
export const REACT_APP_SG_FONT_STYLES =
  process.env.NEXT_PUBLIC_REACT_APP_SG_FONT_STYLES
export const NEWSLETTER_ID = process.env.NEXT_PUBLIC_NEWSLETTER_ID
export const META_ROBOTS = process.env.NEXT_PUBLIC_META_ROBOTS
export const PUBLIC_BASE_URL = process.env.NEXT_PUBLIC_BASE_URL
export const REPUBLIK_PUBLIC_BASE_URL =
  process.env.NEXT_PUBLIC_REPUBLIK_PUBLIC_BASE_URL

export const PIWIK_URL_BASE = process.env.NEXT_PUBLIC_PIWIK_URL_BASE
export const PIWIK_SITE_ID = process.env.NEXT_PUBLIC_PIWIK_SITE_ID
